Repository intuit/auto, pull requests merged in 2018-12, with the labels that each got.

#1 add auto release to CI
  .circleci/config.yml
  src/__tests__/__snapshots__/log-parse.test.ts.snap
Labels: patch

#2 use correct url
  src/git.ts
Labels: patch

#3 ignore invalid user
  src/log-parse.ts
Labels: patch

#9 remove bad changelog
  CHANGELOG.md
Labels: internal, no-release

#10 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: internal, no-release

#11 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: internal, no-release

#12 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: internal, no-release

#13 Rename CONTRIBUTING.md to CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: internal, no-release

#14 Check prCommit.author is defined.
  src/main.ts
Labels: bug, patch

#17 Move typescript-memoize to dependencies
  package.json
Labels: bug, patch

#16 Contributors
  .all-contributorsrc
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package.json
  yarn.lock
Labels: internal, no-release

#19 more badges
  README.md
Labels: internal, no-release

#21 Add documentation website
  .circleci/config.yml
  README.md
  docs/favicon.gif
  docs/images/auto.gif
  docs/index.md
  docs/logo.gif
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/circleci.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  docs/pages/pr-interaction.md
  docs/pages/publishing.md
  package.json
  src/cli/args.ts
  yarn.lock
Labels: internal, no-release

#24 add correct author ;)
  package.json
Labels: internal, no-release

#25 add base url
  package.json
Labels: internal, no-release

#26 Polish
  docs/favicon.gif
  docs/favicon.png
  docs/home.md
  docs/images/changelog.png
  docs/images/comment.png
  docs/images/pr.png
  docs/images/release.png
  docs/images/version.png
  package.json
Labels: documentation, no-release

#27 fix header and theme sidebar
  package.json
Labels: internal, no-release

#28 Update README.md
  README.md
Labels: documentation, no-release

#29 remove weird border
  docs/images/changelog.png
  docs/images/release.png
Labels: documentation, no-release

#30 update ignite
  package.json
  yarn.lock
Labels: internal, no-release

#33 Move login out of CLI
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/github-release.test.ts
  src/__tests__/main.test.ts
  src/bin/__tests__/bin.test.ts
  src/bin/auto.ts
  src/git.ts
  src/github-release.ts
  src/log-parse.ts
  src/main.ts
Labels: patch

#35 Add shipit tool
  docs/index.md
  docs/pages/auto-shipit.md
  scripts/release.sh
  src/main.ts
Labels: minor

#37 Add git user options
  docs/pages/auto-changelog.md
  docs/pages/auto-release.md
  docs/pages/autorc.md
  package.json
  scripts/release.sh
  src/cli/args.ts
  src/github-release.ts
  src/main.ts
Labels: minor

#38 Add Contributor documentation
  README.md
  docs/pages/auto-changelog.md
  docs/pages/getting-started.md
  package.json
  yarn.lock
Labels: documentation, no-release

#39 switch to tiny badges
  README.md
Labels: internal, no-release

#40 center badges
  README.md
Labels: internal, no-release

#42 add init script
  docs/pages/autorc.md
  package.json
  src/cli/args.ts
  src/init.ts
  src/main.ts
  yarn.lock
Labels: minor

#43 update ignite
  package.json
  yarn.lock
Labels: internal, no-release

#46 repository as just a string
  docs/pages/faq.md
  src/utils/package-config.ts
Labels: minor

#47 more troubleshooting docs
  docs/index.md
  docs/pages/faq.md
  docs/pages/troubleshooting.md
Labels: documentation, no-release

#48 Update README.md
  README.md
Labels: documentation, no-release

#49 Add CircleCI Troubleshooting
  .gitignore
  README.md
  docs/pages/circleci.md
  docs/pages/getting-started.md
  package.json
  yarn.lock
Labels: documentation, no-release

#51 Add createLabels tool
  docs/favicon.png
  docs/index.md
  docs/pages/auto-init.md
  docs/pages/getting-started.md
  package.json
  src/__tests__/github-release.test.ts
  src/__tests__/semver.test.ts
  src/cli/args.ts
  src/git.ts
  src/github-release.ts
  src/main.ts
  src/semver.ts
  tsconfig.json
  yarn.lock
Labels: minor

#52 typos in docs
  docs/pages/getting-started.md
Labels: documentation, no-release

#53 Allow user to configure multiple labels to `no-release`
  docs/pages/auto-version.md
  package.json
  src/__tests__/semver.test.ts
  src/cli/args.ts
  src/github-release.ts
  src/main.ts
  src/semver.ts
Labels: minor

#54 add shield icons
  README.md
Labels: documentation

#56 Badge
  README.md
Labels: documentation

#57 Add docs for `noReleaseLabels`
  docs/pages/auto-version.md
  docs/pages/autorc.md
Labels: documentation

#68 rename init-labels -> create-labels
  docs/index.md
  docs/pages/auto-init.md
  docs/pages/getting-started.md
  src/cli/args.ts
  src/main.ts
Labels: minor

#69 print help or missing flag + print all missing flags
  src/cli/__tests__/args.test.ts
  src/cli/args.ts
Labels: minor

#71 Init prompt for changelog labels
  src/init.ts
Labels: minor

#76 Configure changelog labels with create-labels
  src/cli/args.ts
  src/git.ts
  src/github-release.ts
  src/main.ts
Labels: minor

#78 Document process for onboarding an already published repo
  docs/pages/getting-started.md
Labels: documentation

#80 doc ordering
  docs/pages/getting-started.md
Labels: documentation

#81 unneeded long desc on chengelog cli
  src/cli/args.ts
Labels: patch

#85 update deps
  package.json
  src/cli/args.ts
  yarn.lock
Labels: patch

#86 only publish docs with documentation label
  package.json
  scripts/publish-docs.sh
Labels: patch

#87 Clearer wording
  docs/pages/auto-changelog.md
Labels: documentation

#89 missed adding no release labels to `pr-check`
  docs/pages/auto-pr-check.md
  package.json
  src/cli/args.ts
  src/main.ts
Labels: patch

#92 fix version number
  package.json
Labels: internal

#95 only error if there are actually missing args
  src/cli/args.ts
Labels: patch

#96 Change slack flag to boolean
  docs/pages/auto-release.md
  src/cli/args.ts
Labels: patch

#98 pr-check wasn't getting semver labelTexts correctly
  src/main.ts
Labels: patch

#99 url isn't required for pr or pr-check
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  src/cli/args.ts
Labels: patch

#100 Deprecate --major --minor --patch flags
  docs/pages/auto-pr-check.md
  docs/pages/auto-version.md
  src/cli/args.ts
  src/main.ts
Labels: minor

#101 Change `no-release` to `skip-release`
  CHANGELOG.md
  README.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  src/__tests__/github-release.test.ts
  src/__tests__/semver.test.ts
  src/auto-rc.json
  src/cli/args.ts
  src/github-release.ts
  src/init.ts
  src/main.ts
  src/semver.ts
Labels: minor

#104 print link to token create when there is no GH_TOKEN.
  src/__tests__/git.test.ts
  src/cli/args.ts
  src/git.ts
  src/github-release.ts
  src/utils/__tests__/github-token.test.ts
  src/utils/github-token.ts
  src/utils/settings-url.ts
Labels: patch

#105 Application Size
  package.json
  src/__tests__/__snapshots__/git.test.ts.snap
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/__snapshots__/log-parse.test.ts.snap
  src/__tests__/log-parse.test.ts
  src/__tests__/make-commit-from-msg.ts
  src/git.ts
  src/github-release.ts
  src/log-parse.ts
  src/types/gitlog.d.ts
  src/types/parse-git.d.ts
  yarn.lock
Labels: patch

#107 fix(ci): cleaned up circle config
  .circleci/config.yml
  .npmrc
  README.md
  yarn.lock
Labels: internal, skip-release

#110 fix version parsing
  src/__tests__/__snapshots__/git.test.ts.snap
  src/git.ts
  src/types/gitlog.d.ts
Labels: patch

#109 fix dry run
  src/cli/args.ts
  src/main.ts
Labels: patch

#111 update deps
  package.json
  tslint.json
  yarn.lock
Labels: patch

#112 Add @Aghassi as a contributor
  .all-contributorsrc
  README.md
Labels: internal, skip-release

#115 trim subjects for commit messages
  src/log-parse.ts
Labels: patch
