Repository intuit/auto, pull requests merged in 2019-04, with the labels that each got.

#322 Fix issue with warning wrapping section
  docs/pages/autorc.md
Labels: documentation

#325 Octokit
  package.json
  src/git.ts
  yarn.lock
Labels: patch

#327 update ts-jest
  package.json
  yarn.lock
Labels: internal, skip-release

#326 update node types
  package.json
  yarn.lock
Labels: internal, skip-release

#328 update command line args
  package.json
  yarn.lock
Labels: patch

#329 use old addLabels praram because of bug in new one
  src/git.ts
Labels: patch

#335 Add throttling, retry octokit plugins
  package.json
  src/git.ts
  src/types/octokit-plugin-retry.d.ts
  src/types/octokit-plugin-throttling.d.ts
  yarn.lock
Labels: enhancement, minor

#338 Adjust rate limiting retries from 3 to 5
  src/git.ts
Labels: patch

#340 use graphql to get around search rate limits
  package.json
  src/__tests__/__snapshots__/release.test.ts.snap
  src/__tests__/git.test.ts
  src/__tests__/release.test.ts
  src/git.ts
  src/release.ts
  src/types/octokit-graphql.d.ts
  tslint.json
  yarn.lock
Labels: patch

#343 fix bug when no labels exist
  src/__tests__/release.test.ts
  src/release.ts
Labels: patch

#344 Throw an error if extended config fails to load
  src/__tests__/config.test.ts
  src/config.ts
Labels: patch
