Repository intuit/auto, pull requests merged in 2019-06, with the labels that each got.

#455 Independant Canary version reporting + Whitespace in pr-body
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
  plugins/npm/src/index.ts
Labels: patch

#456 NPM Plugin: fix canary versions
  plugins/npm/src/index.ts
Labels: patch

#457 Update AutoChangeLog with Typo Fixes
  docs/pages/auto-changelog.md
Labels: documentation

#459 update octokit
  packages/core/package.json
  plugins/upload-assets/package.json
  yarn.lock
Labels: internal

#460 Git tag Plugin
  README.md
  docs/index.md
  docs/pages/plugins.md
  packages/core/src/auto.ts
  plugins/git-tag/README.md
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/package.json
  plugins/git-tag/src/index.ts
  plugins/git-tag/tsconfig.json
Labels: minor

#461 Conventional Commits Plugin: fix looping issue
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/src/index.ts
Labels: patch

#464 Slack Plugin: fix tag link
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: patch
