Repository intuit/auto, pull requests merged in 2019-10, with the labels that each got.

#583 Ability to edit comments
  .all-contributorsrc
  README.md
  packages/cli/__tests__/args.test.ts
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: minor

#584 proxy support in auto
  .all-contributorsrc
  README.md
  docs/pages/getting-started.md
  packages/core/package.json
  packages/core/src/auto.ts
  packages/core/src/git.ts
  yarn.lock
Labels: enhancement, hacktoberfest, minor

#586 update README.md
  README.md
Labels: documentation, skip-release

#606 update plugin template
  scripts/template-plugin/tsconfig.json
Labels: internal, skip-release

#607 Modern build output
  .circleci/config.yml
  .eslintrc
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/__tests__/auto-env.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/__tests__/release.test.ts
  plugins/chrome/package.json
  plugins/conventional-commits/package.json
  plugins/git-tag/package.json
  plugins/jira/package.json
  plugins/jira/src/index.ts
  plugins/maven/package.json
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/omit-commits/package.json
  plugins/omit-release-notes/package.json
  plugins/released/package.json
  plugins/slack/package.json
  plugins/twitter/package.json
  plugins/upload-assets/package.json
  scripts/template-plugin/package.json
  tsconfig.json
  yarn.lock
Labels: internal, skip-release

#587 Crates (Rust language) plugin
  .all-contributorsrc
  README.md
  docs/index.md
  docs/pages/writing-plugins.md
  plugins/crates/README.md
  plugins/crates/__tests__/crates.test.ts
  plugins/crates/package.json
  plugins/crates/src/index.ts
  plugins/crates/tsconfig.json
  tsconfig.dev.json
  yarn.lock
Labels: minor

#608 fix install names in readmes
  plugins/crates/README.md
  plugins/maven/README.md
Labels: documentation, skip-release

#609 only add hash to canary version if no pr or build detected
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#585 Switch to command-line-application and command-line-docs
  .gitignore
  README.md
  docs/generate-command-docs.js
  docs/index.md
  docs/pages/auto-canary.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-body.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr-status.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/extras/changelog.md
  docs/pages/extras/label.md
  docs/pages/extras/release.md
  docs/pages/extras/version.md
  docs/pages/getting-started.md
  package.json
  packages/cli/__tests__/args.test.ts
  packages/cli/package.json
  packages/cli/src/parse-args.ts
  scripts/publish-docs.sh
  yarn.lock
Labels: internal

#466 New Plugin: Amazon S3
  README.md
  docs/index.md
  docs/pages/plugins.md
  packages/core/src/auto.ts
  plugins/chrome/README.md
  plugins/chrome/src/index.ts
  plugins/git-tag/README.md
  plugins/npm/README.md
  plugins/npm/src/index.ts
  plugins/omit-commits/README.md
  plugins/omit-release-notes/README.md
  plugins/s3/README.md
  plugins/s3/__tests__/s3.test.ts
  plugins/s3/package.json
  plugins/s3/src/index.ts
  plugins/s3/tsconfig.json
  plugins/twitter/README.md
  scripts/template-plugin/README.md
  yarn.lock
Labels: minor

#611 Move git-tag to "Package Manager Plugins"
  docs/index.md
Labels: documentation, skip-release

#613 Fix windows git refspec problem
  plugins/chrome/src/index.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/crates/src/index.ts
  plugins/git-tag/src/index.ts
  plugins/maven/src/index.ts
  plugins/npm/src/index.ts
Labels: patch

#626 better error messaging when tags aren't present
  packages/core/package.json
  packages/core/src/git.ts
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
Labels: patch
