Repository intuit/auto, pull requests merged in 2019-03, with the labels that each got.

#300 update deps
  package.json
  src/utils/exec-promise.ts
  yarn.lock
Labels: internal

#302 fixing a typo
  README.md
Labels: documentation, skip-release

#306 update deps
  package.json
  src/__tests__/git.test.ts
  src/__tests__/release.test.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/types/registry-url.d.ts
  yarn.lock
Labels: internal

#297 Remove auth in error responses if it's present
  src/__tests__/auto.test.ts
  src/__tests__/git.test.ts
  src/auto.ts
  src/git.ts
Labels: patch

#307 fix typo in docs
  docs/index.md
Labels: documentation, skip-release

#310 last ditch search for related PRs
  src/__tests__/__snapshots__/release.test.ts.snap
  src/__tests__/release.test.ts
  src/release.ts
Labels: patch

#311 only add users once to changelog
  src/__tests__/__snapshots__/release.test.ts.snap
  src/changelog.ts
Labels: patch
