Repository intuit/auto, pull requests merged in 2019-07, with the labels that each got.

#474 Add a little extra error handling around plugin loading
  packages/core/src/utils/load-plugins.ts
Labels: patch

#475 feat(slack): add custom slack at targets
  .all-contributorsrc
  README.md
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#478 Fix type error with changelog hook
  packages/core/src/utils/make-hooks.ts
Labels: patch, skip-release

#480 Rework plugin importing logic
  docs/pages/plugins.md
  packages/core/src/utils/load-plugins.ts
Labels: patch

#479 Remove pr semver check
  .circleci/config.yml
Labels: internal, skip-release

#485 Update README.md
  README.md
Labels: documentation, skip-release

#486 Fix links in docs
  docs/index.md
  docs/pages/auto-pr-status.md
  package.json
  yarn.lock
Labels: documentation, skip-release

#495 change to dependabot
  package.json
Labels: internal, skip-release

#496 fix docs
  package.json
  yarn.lock
Labels: skip-release

#497 fix logging error in pr-check
  packages/core/src/auto.ts
Labels: patch
