Repository intuit/auto, pull requests merged in 2019-12, with the labels that each got.

#746 move git clean check to core
  packages/core/src/__tests__/auto-canary-in-pr-ci.test.ts
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: major

#750 Slight improvements to GitHub actions docs
  docs/pages/build-platforms/github-actions.md
Labels: documentation, skip-release

#752 Making the docs a little more solid...
  docs/pages/build-platforms/github-actions.md
Labels: documentation, skip-release

#753 fix docs build issue
  docs/pages/build-platforms/github-actions.md
Labels: documentation, skip-release

#747 move determineNextVersion to core
  packages/core/src/auto.ts
  plugins/git-tag/src/index.ts
  plugins/npm/src/index.ts
Labels: minor

#755 docs(introduction): fix typo
  docs/pages/introduction.md
Labels: documentation, skip-release

#756 add more defaults to all-contributors plugin
  plugins/all-contributors/src/index.ts
Labels: minor

#751 Simplify label configuration
  docs/pages/autorc.md
  docs/pages/extras/version.md
  package.json
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/__tests__/config.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto-rc.json
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/release.ts
  packages/core/src/semver.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: major

#768 Don't create a version commit for prereleases
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/auto.ts
  packages/core/src/utils/__tests__/exec-promise.test.ts
  packages/core/src/utils/exec-promise.ts
  plugins/all-contributors/package.json
  plugins/chrome/package.json
  plugins/conventional-commits/package.json
  plugins/crates/package.json
  plugins/first-time-contributor/package.json
  plugins/git-tag/package.json
  plugins/jira/package.json
  plugins/maven/package.json
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/omit-commits/package.json
  plugins/omit-release-notes/package.json
  plugins/released/package.json
  plugins/s3/package.json
  plugins/slack/package.json
  plugins/twitter/package.json
  plugins/upload-assets/package.json
Labels: patch

#769 reset monorepo version for next branch
  lerna.json
Labels: internal, skip-release

#770 Add glob support to the upload-assets plugin
  plugins/upload-assets/README.md
  plugins/upload-assets/__tests__/test-assets/test-2.txt
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
  yarn.lock
Labels: minor

#771 Deprecate "--very-verbose, -w" in favor of "-vv"
  .circleci/config.yml
  packages/cli/README.md
  packages/cli/src/parse-args.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: major

#772 More resilient test case
  plugins/upload-assets/__tests__/upload-assets.test.ts
Labels: internal

#773 next: post comment w/prerelease version on prerelease PR branches
  packages/cli/src/parse-args.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#777 add release notes to prerelease PRs
  packages/core/src/auto.ts
Labels: minor

#778 do not add labels or comments to prerelease branch PRs
  .all-contributorsrc
  CHANGELOG.md
  Formula/auto.rb
  README.md
  docs/generate-command-docs.js
  docs/images/next-branch.png
  docs/index.md
  docs/pages/build-platforms/github-actions.md
  docs/pages/extras/shipit.md
  docs/pages/introduction.md
  lerna.json
  package.json
  packages/cli/package.json
  packages/cli/src/parse-args.ts
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/release.ts
  plugins/all-contributors/package.json
  plugins/all-contributors/src/index.ts
  plugins/chrome/package.json
  plugins/conventional-commits/README.md
  plugins/conventional-commits/package.json
  plugins/crates/package.json
  plugins/first-time-contributor/package.json
  plugins/first-time-contributor/src/index.ts
  plugins/git-tag/package.json
  plugins/jira/package.json
  plugins/maven/package.json
  plugins/npm/package.json
  plugins/omit-commits/package.json
  plugins/omit-release-notes/package.json
  plugins/released/__tests__/released-label.test.ts
  plugins/released/package.json
  plugins/released/src/index.ts
  plugins/s3/package.json
  plugins/slack/package.json
  plugins/twitter/__tests__/twitter.test.ts
  plugins/twitter/package.json
  plugins/twitter/src/index.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
  scripts/update-tap.js
  typings/endent.d.ts
  yarn.lock
Labels: patch

#779 add tests
  docs/pages/extras/shipit.md
  package.json
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/__tests__/package-config.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/s3/__tests__/s3.test.ts
Labels: internal

#780 do not call afterRelease hooks during dry run
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: patch

#783 omit commits that have already been released
  package.json
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
Labels: patch

#782 create v8 announcement blog
  docs/blog/v8.md
  docs/pages/extras/shipit.md
  package.json
  packages/cli/src/parse-args.ts
  yarn.lock
Labels: blog-post

#786 only grant contributions for work in commit
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/log-parse.ts
  packages/core/src/release.ts
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
  plugins/npm/src/index.ts
Labels: patch

#788 docs(publishing): add period after sentence
  docs/pages/publishing.md
Labels: documentation, skip-release

#790 add context
  .circleci/config.yml
Labels: internal, skip-release

#792 add canaryScope option for more secure PR builds
  .circleci/config.yml
  docs/blog/npm-canary-scope.md
  package.json
  plugins/npm/README.md
  plugins/npm/src/index.ts
  plugins/npm/src/utils.ts
Labels: minor

#794 fix bug where merging a none would skip previously meged semver bump
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/semver.ts
Labels: patch

#795 add diagrams
  docs/blog/npm-canary-scope.md
  docs/images/complete-auto.png
  docs/images/default-auto.png
  docs/pages/extras/shipit.md
  plugins/npm/README.md
Labels: documentation

#797 Fix `none` releases: they were not handling extra labels
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/auto.ts
  packages/core/src/semver.ts
Labels: patch

#796 omit next branch PR Title from being in release notes
  docs/pages/extras/next.md
  docs/pages/extras/shipit.md
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/changelog.ts
  packages/core/src/release.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/npm/__tests__/monorepo-log.test.ts
Labels: patch

#798 touch up blog post
  docs/blog/npm-canary-scope.md
Labels: blog-post

#799 Slight improvements to label configuration docs
  docs/pages/autorc.md
  docs/pages/extras/changelog.md
  docs/pages/extras/release.md
  docs/pages/publishing.md
Labels: documentation

#800 release: add flag to publish prerelease
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#810 release: detect prerelease branch + be smarter about commit range
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  plugins/git-tag/src/index.ts
  plugins/npm/src/index.ts
Labels: minor

#811 version: detect prerelease branch
  packages/core/src/auto.ts
  packages/core/src/semver.ts
Labels: minor

#813 alias the canary scope
  packages/cli/package.json
  packages/cli/src/bin/auto.ts
  plugins/npm/README.md
  plugins/npm/src/index.ts
  typings/module-alias.d.ts
  yarn.lock
Labels: patch

#814 Version branches
  Formula/auto.rb
  lerna.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/release.ts
  plugins/all-contributors/CHANGELOG.md
  plugins/all-contributors/package.json
  plugins/chrome/CHANGELOG.md
  plugins/chrome/package.json
  plugins/conventional-commits/CHANGELOG.md
  plugins/conventional-commits/package.json
  plugins/crates/CHANGELOG.md
  plugins/crates/package.json
  plugins/first-time-contributor/CHANGELOG.md
  plugins/first-time-contributor/package.json
  plugins/git-tag/CHANGELOG.md
  plugins/git-tag/package.json
  plugins/git-tag/src/index.ts
  plugins/jira/CHANGELOG.md
  plugins/jira/package.json
  plugins/maven/CHANGELOG.md
  plugins/maven/package.json
  plugins/npm/CHANGELOG.md
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/omit-commits/CHANGELOG.md
  plugins/omit-commits/package.json
  plugins/omit-release-notes/CHANGELOG.md
  plugins/omit-release-notes/package.json
  plugins/released/CHANGELOG.md
  plugins/released/package.json
  plugins/s3/CHANGELOG.md
  plugins/s3/package.json
  plugins/slack/CHANGELOG.md
  plugins/slack/package.json
  plugins/twitter/CHANGELOG.md
  plugins/twitter/package.json
  plugins/upload-assets/CHANGELOG.md
  plugins/upload-assets/package.json
Labels: minor

#816 update docs to show JS plugins and how to use versionBranches
  docs/pages/autorc.md
  docs/pages/extras/shipit.md
  docs/pages/writing-plugins.md
  scripts/update-tap.js
Labels: documentation

#817 canary hook can return void to not bail
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#819 only access auto login if it all exists
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
Labels: patch

#820 determine next version using by omitting tags from master
  packages/core/src/__tests__/git.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/utils/exec-promise.ts
  packages/core/src/utils/logger.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/released/__tests__/released-label.test.ts
Labels: patch

#821 add context of what type of release was made during shipit
  docs/pages/writing-plugins.md
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
Labels: minor

#824 Add more logs for next release calculation
  packages/core/src/git.ts
  plugins/npm/src/index.ts
Labels: patch

#827 next: check origin head instead of local branch for tags
  packages/core/src/git.ts
Labels: patch

#822 Add documentation and tests for label changelog label section assignment behavior
  docs/pages/autorc.md
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
Labels: documentation

#842 docs: fixed incorrect afterRelease hook object
  docs/pages/writing-plugins.md
Labels: documentation
