Repository intuit/auto, pull requests merged in 2019-11, with the labels that each got.

#642 more reliable docs publish
  package.json
  scripts/publish-docs.sh
  yarn.lock
Labels: internal, skip-release

#655 fix issue with latest enterprise compat plugin
  packages/core/package.json
  yarn.lock
Labels: patch

#659 Fix creating old changelogs
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: patch

#660 Fix multiple first-time-contributor thank you
  plugins/first-time-contributor/__tests__/__snapshots__/first-time-contributor.test.ts.snap
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/first-time-contributor/src/index.ts
Labels: patch

#661 Fix wrong author in changelog
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/changelog.ts
Labels: patch

#658 NPM: manage a changelog for each sub-package in monorepo
  docs/pages/writing-plugins.md
  package.json
  packages/core/src/__tests__/__snapshots__/git.test.ts.snap
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/release.ts
  packages/core/src/utils/make-hooks.ts
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/npm/README.md
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/src/index.ts
  yarn.lock
Labels: minor

#663 Fix GitHub Release's release notes for monorepo during shipit
  plugins/npm/src/index.ts
Labels: patch

#664 clarify plugin docs
  docs/pages/plugins.md
Labels: documentation, skip-release

#665 Add JSDoc comment to most everything
  .eslintrc
  docs/generate-command-docs.js
  docs/pages/writing-plugins.md
  package.json
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/__snapshots__/log-parse.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/config.test.ts
  packages/core/src/__tests__/make-commit-from-msg.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/log-parse.ts
  packages/core/src/plugins/filter-non-pull-request.ts
  packages/core/src/release.ts
  packages/core/src/semver.ts
  packages/core/src/utils/__tests__/test-plugin.ts
  packages/core/src/utils/exec-promise.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/logger.ts
  packages/core/src/utils/make-hooks.ts
  packages/core/src/utils/try-require.ts
  plugins/all-contributors/src/index.ts
  plugins/chrome/src/index.ts
  plugins/conventional-commits/src/index.ts
  plugins/crates/src/index.ts
  plugins/first-time-contributor/src/index.ts
  plugins/git-tag/src/index.ts
  plugins/jira/src/index.ts
  plugins/maven/src/index.ts
  plugins/npm/__tests__/package-config.test.ts
  plugins/npm/src/index.ts
  plugins/npm/src/package-config.ts
  plugins/npm/src/set-npm-token.ts
  plugins/npm/src/utils.ts
  plugins/omit-commits/src/index.ts
  plugins/omit-release-notes/src/index.ts
  plugins/released/src/index.ts
  plugins/s3/src/index.ts
  plugins/slack/src/index.ts
  plugins/twitter/src/index.ts
  plugins/upload-assets/src/index.ts
  scripts/template-plugin/src/index.ts
  yarn.lock
Labels: documentation, skip-release

#667 must trust github for docs to publish
  .circleci/config.yml
  docs/pages/autorc.md
Labels: internal, skip-release

#678 warn when canary not implemented
  docs/pages/autorc.md
  package.json
  packages/core/src/__tests__/auto-canary-in-pr-ci.test.ts
  packages/core/src/auto.ts
  yarn.lock
Labels: patch

#680 Rewrite README Issue #666
  packages/cli/README.md
Labels: documentation, skip-release

#682 detect PR number when running "auto label" without "--pr"
  packages/core/src/auto.ts
Labels: minor

#683 Fix bug where 'all-contributors' plugin wasn't picking up changes
  .all-contributorsrc
  README.md
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: patch

#684 Default to `git-tag` plugin when run from binary
  README.md
  docs/pages/autorc.md
  docs/pages/extras/changelog.md
  docs/pages/extras/label.md
  docs/pages/plugins.md
  docs/pages/troubleshooting.md
  packages/cli/README.md
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  plugins/git-tag/README.md
  plugins/npm/README.md
Labels: minor

#685 add docs on how to use within a lerna monorepo
  plugins/npm/README.md
Labels: documentation, skip-release

#686 add docs on merging quickly
  docs/index.md
  docs/pages/quick-merge.md
Labels: documentation, skip-release

#688 modernize circleci docs
  docs/pages/circleci.md
Labels: documentation, skip-release

#689 add more platform docs
  docs/index.md
  docs/pages/build-platforms/circleci.md
  docs/pages/build-platforms/github-actions.md
  docs/pages/build-platforms/travis.md
Labels: documentation, skip-release

#690 add jenkins usage
  docs/index.md
  docs/pages/build-platforms/jenkins.md
Labels: documentation, skip-release

#679 add non-npm docs
  docs/generate-command-docs.js
  docs/index.md
  docs/pages/getting-started.md
  docs/pages/non-npm.md
  package.json
  yarn.lock
Labels: documentation, skip-release

#691 add logs for where plugins were found
  packages/core/src/utils/load-plugins.ts
Labels: patch

#694 automatically update brew formula
  Formula/auto.rb
  docs/pages/non-npm.md
  package.json
  scripts/update-tap.js
Labels: minor, skip-release

#695 correct docs
  docs/pages/non-npm.md
Labels: patch

#696 correct grammar
  docs/pages/non-npm.md
Labels: documentation, patch

#697 match behavior between lerna and npm when pushing git tags
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  scripts/update-tap.js
Labels: patch

#698 More flexible monorepo publishing
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  scripts/update-tap.js
Labels: patch

#699 update ignite
  package.json
  yarn.lock
Labels: dependencies

#700 force docs publish
  docs/pages/writing-plugins.md
Labels: documentation, skip-release

#711 Upgrade to Typescript 3.7
  .eslintrc
  package.json
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/plugins/filter-non-pull-request.ts
  packages/core/src/release.ts
  plugins/maven/src/index.ts
  plugins/npm/src/index.ts
  plugins/npm/src/set-npm-token.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  tsconfig.json
  yarn.lock
Labels: internal, skip-release

#701 Modified packages/cli README
  packages/cli/README.md
Labels: documentation

#712 remove references to "npm" plugin in "released" docs
  plugins/released/README.md
Labels: documentation, skip-release

#713 Update autorc.md
  docs/pages/autorc.md
Labels: documentation, skip-release

#726 Add ability for "next" branch publishing
  .circleci/config.yml
  package.json
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/utils/make-hooks.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#727 must set git user before publishing so we know we can commit
  packages/core/src/auto.ts
Labels: patch

#728 don't run released plugin on "next" branch PRs
  plugins/released/src/index.ts
Labels: patch

#729 remove old use of prerelease label + add prerelease label to released plugin
  docs/pages/extras/version.md
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/auto-rc.json
  packages/core/src/git.ts
  packages/core/src/release.ts
  packages/core/src/semver.ts
  plugins/released/README.md
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: major

#730 allow user to configure what branches are treated as prerelease branches
  docs/pages/autorc.md
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/release.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#731 shipit: add flag to only publish to 'latest' tag when "release" label is present
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  plugins/npm/src/index.ts
Labels: minor

#732 implement prerelease branches for git-tag plugin
  plugins/git-tag/src/index.ts
Labels: minor

#733 implment dry-run flag for next command
  packages/cli/src/run.ts
  packages/core/src/auto.ts
Labels: minor

#734 change getPreviousVersion hook args. can access prefixRelease from root class instead
  docs/pages/writing-plugins.md
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/chrome/src/index.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/crates/src/index.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: major

#735 ensure canary versions dont use extra bumps
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch
