Repository intuit/auto, pull requests merged in 2019-05, with the labels that each got.

#348 comment, pr, and pr-check detect PR number in CI
  docs/pages/auto-comment.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  package.json
  src/__tests__/auto-comment.test.ts
  src/__tests__/auto.test.ts
  src/auto.ts
  src/cli/args.ts
  yarn.lock
Labels: minor

#350 Graphql url config
  docs/pages/autorc.md
  src/auto.ts
  src/cli/args.ts
  src/git.ts
  src/init.ts
  src/release.ts
Labels: minor

#349 canary command
  .circleci/config.yml
  docs/index.md
  docs/pages/auto-canary.md
  package.json
  src/__tests__/auto-canary-in-ci.test.ts
  src/__tests__/auto.test.ts
  src/auto.ts
  src/cli/args.ts
  src/main.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/make-hooks.ts
  yarn.lock
Labels: minor

#352 add forcePublish config option to npm plugin
  docs/index.md
  docs/pages/npm.md
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/__tests__/load-plugin.test.ts
Labels: minor

#354 increase buffer for situations when user has a LOT of unpublished work
  src/git.ts
  src/types/gitlog.d.ts
Labels: patch

#356 enable loglevel silly for npm/lerna when in verbose or veryVerbose mode
  src/auto.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/logger.ts
Labels: minor

#359 changelog includes any commit that has a PR parsed from the commit message
  src/__tests__/__snapshots__/release.test.ts.snap
  src/__tests__/release.test.ts
  src/release.ts
Labels: patch

#360 when canary is run locally it uses the commits SHA instead of PR + Build
  src/__tests__/auto.test.ts
  src/auto.ts
  src/git.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/__tests__/exec-promise.test.ts
  src/utils/exec-promise.ts
Labels: minor

#361 update docs
  docs/pages/auto-canary.md
  src/cli/args.ts
Labels: documentation

#363 make logLevel available on the logger
  src/auto.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/logger.ts
Labels: patch

#362 Override any env var set in the .env
  docs/pages/getting-started.md
  src/__tests__/auto-env.test.ts
  src/auto.ts
Labels: patch

#365 remove accidental log
  src/plugins/npm/index.ts
Labels: internal

#367 fix bug when tying to publish canary for PR with skip-release label
  src/__tests__/auto.test.ts
  src/auto.ts
Labels: patch

#366 skip releases for greenkeeper + make special changelog section
  package.json
  src/__tests__/auto.test.ts
Labels: internal, skip-release

#368 add blog
  docs/blog/using-shipit.md
  docs/blog/why.md
  package.json
  yarn.lock
Labels: documentation, skip-release

#351 Calling `shipit` in PR in CI creates canary release
  .circleci/config.yml
  README.md
  docs/pages/auto-changelog.md
  docs/pages/auto-label.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  docs/pages/publishing.md
  package.json
  src/__tests__/__snapshots__/auto.test.ts.snap
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/auto-canary-in-pr-ci.test.ts
  src/__tests__/auto.test.ts
  src/__tests__/changelog.test.ts
  src/__tests__/git.test.ts
  src/__tests__/release.test.ts
  src/auto.ts
  src/changelog.ts
  src/cli/args.ts
  src/git.ts
  src/init.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/plugins/released/__tests__/released-label.test.ts
  src/plugins/released/index.ts
  src/release.ts
Labels: major

#371 shipit will publish a canary locally when not on master
  README.md
  docs/pages/auto-shipit.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  src/__tests__/auto-canary-local.test.ts
  src/auto.ts
  src/cli/args.ts
Labels: patch

#372 New Post: Merging PRs to other PRs
  docs/blog/pr-in-progress.md
  docs/blog/using-shipit.md
  docs/blog/why.md
  docs/images/pr-to-pr.png
  package.json
  yarn.lock
Labels: blog-post

#374 Restrict config type
  docs/pages/autorc.md
  src/__tests__/auto.test.ts
  src/__tests__/config.test.ts
  src/config.ts
Labels: major, skip-release

#373 Support Lerna Independent mode
  docs/pages/writing-plugins.md
  src/__tests__/auto-canary-in-pr-ci.test.ts
  src/__tests__/auto-canary-local.test.ts
  src/__tests__/auto.test.ts
  src/auto.ts
  src/plugins/npm/__tests__/__snapshots__/monorepo-log.test.ts.snap
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/release.ts
  src/utils/make-hooks.ts
Labels: minor

#377 Better get by username/email error handling
  src/__tests__/git.test.ts
  src/git.ts
Labels: patch

#378 report back correct versions when running canary
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
Labels: patch

#379 add `auto pr-body` to add info to pr bodies + canary posts to body instead of comment
  docs/index.md
  docs/pages/auto-pr-body.md
  src/__tests__/auto-canary-in-pr-ci.test.ts
  src/__tests__/auto.test.ts
  src/__tests__/git.test.ts
  src/auto.ts
  src/cli/args.ts
  src/git.ts
  src/main.ts
Labels: minor

#383 Correct reported lerna independent version
  src/__tests__/auto-canary-in-pr-ci.test.ts
  src/__tests__/auto.test.ts
  src/auto.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
Labels: patch

#384 Error on uncommited files when before running canary + version
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
Labels: minor

#385 update deps for things greenkeeper failed on
  package.json
  yarn.lock
Labels: greenkeeper

#387 split off useless hash from version
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
Labels: patch

#388 must await posting to the PR body
  src/auto.ts
Labels: patch

#389 use correct variable in pr-body success message
  src/auto.ts
Labels: patch

#386 remove getGitHubToken function
  src/__tests__/auto.test.ts
  src/__tests__/release.test.ts
  src/auto.ts
  src/config.ts
  src/utils/__tests__/github-token.test.ts
  src/utils/github-token.ts
Labels: patch

#391 Fix typo in introduction documentation
  docs/pages/introduction.md
Labels: documentation

#380 Release notes
  docs/pages/auto-changelog.md
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/__snapshots__/release.test.ts.snap
  src/__tests__/changelog.test.ts
  src/__tests__/release.test.ts
  src/changelog.ts
  src/git.ts
  src/log-parse.ts
  src/release.ts
Labels: minor

#392 ensure major minor and patch get to changelog in that order
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/changelog.test.ts
  src/__tests__/git.test.ts
  src/changelog.ts
  src/git.ts
Labels: patch

#393 add page for conventional-commits plugin
  docs/index.md
  docs/pages/conventional-commits.md
Labels: documentation

#396 Fix grammar in getting started documentation
  docs/pages/getting-started.md
Labels: documentation

#394 conventional-commits plugin blog post
  docs/blog/both-worlds.md
  package.json
  yarn.lock
Labels: blog-post

#395 conventional-commit plugin: should omit PR merge commits when a commit in the PR has CC commit message
  docs/pages/conventional-commits.md
  package.json
  src/plugins/conventional-commits/__tests__/conventional-commits.test.ts
  src/plugins/conventional-commits/index.ts
Labels: patch

#399 lerna no-force-publish release conflict
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/auto.test.ts
  src/__tests__/changelog.test.ts
  src/auto.ts
Labels: patch

#400 Greenkeeper/@octokit/plugin throttling 2.5.0
  package.json
  yarn.lock
Labels: greenkeeper

#401 update canary to update pr body when there is a pr
  src/__tests__/auto.test.ts
  src/auto.ts
Labels: minor

#402 update docs for canary
  docs/pages/auto-canary.md
  src/cli/args.ts
Labels: documentation, skip-release

#404 fix jira PR titles without additional subject
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/changelog.test.ts
  src/__tests__/log-parse.test.ts
  src/changelog.ts
  src/log-parse.ts
Labels: patch

#403 Add --delete to `comment` and `pr-body`
  docs/pages/auto-comment.md
  docs/pages/auto-pr-body.md
  src/__tests__/auto.test.ts
  src/__tests__/git.test.ts
  src/auto.ts
  src/cli/__tests__/args.test.ts
  src/cli/args.ts
  src/git.ts
  src/plugins/released/__tests__/released-label.test.ts
  src/plugins/released/index.ts
Labels: minor

#405 typo
  docs/pages/autorc.md
Labels: documentation

#407 Move slack functionality to a plugin
  docs/pages/auto-release.md
  docs/pages/autorc.md
  docs/pages/slack.md
  src/__tests__/__snapshots__/auto.test.ts.snap
  src/__tests__/auto.test.ts
  src/__tests__/release.test.ts
  src/auto.ts
  src/cli/args.ts
  src/plugins/released/__tests__/released-label.test.ts
  src/plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  src/plugins/slack/__tests__/slack.test.ts
  src/plugins/slack/index.ts
  src/release.ts
  src/utils/__tests__/slack.test.ts
  src/utils/make-hooks.ts
  src/utils/slack.ts
Labels: major

#408 Move jira functionality to plugin
  docs/pages/auto-changelog.md
  docs/pages/auto-release.md
  docs/pages/autorc.md
  docs/pages/jira.md
  docs/pages/writing-plugins.md
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/changelog.test.ts
  src/__tests__/config.test.ts
  src/__tests__/log-parse.test.ts
  src/auto-rc.json
  src/changelog.ts
  src/cli/args.ts
  src/init.ts
  src/log-parse.ts
  src/plugins/jira/__tests__/jira.test.ts
  src/plugins/jira/index.ts
  src/plugins/npm/__tests__/__snapshots__/monorepo-log.test.ts.snap
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/plugins/npm/index.ts
  src/release.ts
  src/utils/make-hooks.ts
Labels: major

#409 Factor out filter accounts plugin
  docs/index.md
  docs/pages/plugins/chrome.md
  docs/pages/plugins/conventional-commits.md
  docs/pages/plugins/filter-accounts.md
  docs/pages/plugins/jira.md
  docs/pages/plugins/npm.md
  docs/pages/plugins/released.md
  docs/pages/plugins/slack.md
  src/__tests__/log-parse.test.ts
  src/log-parse.ts
  src/plugins/filter-accounts/__tests__/filter-accounts.test.ts
  src/plugins/filter-accounts/index.ts
  src/utils/load-plugins.ts
Labels: major

#411 Parse monorepo packages outside of `packages` directory
  package.json
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#413 Rename `auto pr` to `auto pr-status`
  docs/pages/auto-pr-status.md
  packages/cli/__tests__/args.test.ts
  packages/cli/src/args.ts
  packages/cli/src/main.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/cli-args.ts
Labels: major

#416 Split args type between core and cli
  packages/cli/__tests__/args.test.ts
  packages/cli/__tests__/main.test.ts
  packages/cli/src/bin/auto.ts
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto-canary-in-pr-ci.test.ts
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-comment.test.ts
  packages/core/src/__tests__/auto-env.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/init.ts
  packages/core/src/release.ts
  plugins/released/__tests__/released-label.test.ts
Labels: internal

#418 Bundle `auto` for all major platforms
  .circleci/config.yml
  docs/pages/getting-started.md
  package.json
  packages/cli/package.json
  packages/cli/src/parse-args.ts
  packages/core/src/utils/load-plugins.ts
  yarn.lock
Labels: minor

#420 afterRelease returns an object so future updates will be easier
  docs/pages/writing-plugins.md
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/utils/make-hooks.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: major

#421 add upload assets plugin
  README.md
  docs/index.md
  docs/pages/introduction.md
  docs/pages/plugins.md
  package.json
  packages/core/src/git.ts
  plugins/upload-assets/README.md
  plugins/upload-assets/__tests__/test-assets/macos
  plugins/upload-assets/__tests__/test-assets/test.txt
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
  plugins/upload-assets/tsconfig.json
  yarn.lock
Labels: minor

#425 Change filter-accounts plugin to omit-commits plugin
  README.md
  docs/index.md
  docs/pages/plugins.md
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/make-commit-from-msg.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
  plugins/filter-accounts/README.md
  plugins/filter-accounts/__tests__/filter-accounts.test.ts
  plugins/filter-accounts/src/index.ts
  plugins/omit-commits/README.md
  plugins/omit-commits/__tests__/omit-commits.test.ts
  plugins/omit-commits/package.json
  plugins/omit-commits/src/index.ts
  plugins/omit-commits/tsconfig.json
Labels: major

#427 new hook: omit prs from release notes + add omit-release-notes plugin
  README.md
  docs/pages/plugins.md
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/changelog.ts
  packages/core/src/utils/make-hooks.ts
  plugins/omit-commits/README.md
  plugins/omit-release-notes/README.md
  plugins/omit-release-notes/package.json
  plugins/omit-release-notes/src/index.ts
  plugins/omit-release-notes/tsconfig.json
Labels: minor

#428 Use @auto-it scope
  docs/pages/troubleshooting.md
  package.json
  packages/cli/package.json
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/README.md
  packages/core/package.json
  packages/core/src/utils/load-plugins.ts
  plugins/chrome/README.md
  plugins/chrome/package.json
  plugins/chrome/src/index.ts
  plugins/conventional-commits/README.md
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/package.json
  plugins/conventional-commits/src/index.ts
  plugins/jira/README.md
  plugins/jira/__tests__/jira.test.ts
  plugins/jira/package.json
  plugins/jira/src/index.ts
  plugins/npm/README.md
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/__tests__/set-npm-token.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/npm/src/set-npm-token.ts
  plugins/omit-commits/README.md
  plugins/omit-commits/__tests__/omit-commits.test.ts
  plugins/omit-commits/package.json
  plugins/omit-commits/src/index.ts
  plugins/omit-release-notes/README.md
  plugins/omit-release-notes/package.json
  plugins/omit-release-notes/src/index.ts
  plugins/released/README.md
  plugins/released/__tests__/released-label.test.ts
  plugins/released/package.json
  plugins/released/src/index.ts
  plugins/slack/README.md
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/package.json
  plugins/slack/src/index.ts
  plugins/twitter/README.md
  plugins/twitter/__tests__/twitter.test.ts
  plugins/twitter/package.json
  plugins/twitter/src/index.ts
  plugins/upload-assets/README.md
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
Labels: major

#430 Add monorepo plugin create command
  .prettierignore
  README.md
  package.json
  scripts/create-plugin.js
  scripts/template-plugin/README.md
  scripts/template-plugin/__tests__/{{kebab}}.test.ts
  scripts/template-plugin/package.json
  scripts/template-plugin/src/index.ts
  scripts/template-plugin/tsconfig.json
  tslint.json
  yarn.lock
Labels: internal

#435 fix bundling plugin issue
  .circleci/config.yml
  .gitignore
  package.json
  packages/cli/package.json
  packages/core/src/utils/load-plugins.ts
  yarn.lock
Labels: patch

#437 fix bundle step, must gzip correct folder
  packages/cli/package.json
Labels: internal, skip-release

#438 fix changelog indentation
  packages/core/src/changelog.ts
Labels: patch

#439 Fix conventional commits link
  README.md
Labels: documentation, skip-release

#441 Remove bin entry from core
  packages/core/package.json
Labels: patch

#444 fall back to normal require for npx and global usage
  packages/core/src/utils/__tests__/try-require.test.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/try-require.ts
Labels: patch

#445 Update README.md
  README.md
Labels: documentation, skip-release

#446 stop using --canary flag in npm package
  plugins/npm/src/index.ts
Labels: patch

#448 Get docs publishing
  docs/pages/circleci.md
  scripts/publish-docs.sh
Labels: documentation, skip-release

#450 Respect author in config
  packages/core/src/auto.ts
Labels: patch

#451 Lerna independent mode bugs
  packages/core/src/auto.ts
  packages/core/src/release.ts
  packages/core/src/utils/make-hooks.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/npm/__tests__/__snapshots__/monorepo-log.test.ts.snap
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/omit-release-notes/__tests__/omit-release-notes.test.ts
Labels: patch

#452 Changelog bugs
  packages/core/src/__tests__/git.test.ts
  packages/core/src/changelog.ts
  packages/core/src/git.ts
Labels: patch
