Repository intuit/auto, pull requests merged in 2019-01, with the labels that each got.

#116 add snyk badge
  README.md
Labels: internal, skip-release

#117 update ignite
  package.json
  yarn.lock
Labels: internal, skip-release

#118 More Repo Usage
  README.md
Labels: internal, skip-release

#120 Convert 'Github' to 'GitHub'
  CODE_OF_CONDUCT.md
  README.md
  docs/home.md
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  docs/pages/troubleshooting.md
  package.json
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/git-changed-packages.test.ts
  src/__tests__/git.test.ts
  src/__tests__/github-release.test.ts
  src/cli/args.ts
  src/git.ts
  src/github-release.ts
  src/init.ts
  src/main.ts
  src/utils/__tests__/package-config.test.ts
  src/utils/github-token.ts
  src/utils/package-config.ts
Labels: patch

#119 Don't crash when there is no author hash in the package.json
  src/main.ts
Labels: patch

#121 Include a log when creating a new labels about what those labels are
  src/__tests__/github-release.test.ts
  src/git.ts
  src/github-release.ts
Labels: patch

#125 only set git user if one isn't already set
  src/main.ts
Labels: patch

#126 print only email when name is not present
  src/__tests__/__snapshots__/log-parse.test.ts.snap
  src/__tests__/log-parse.test.ts
  src/log-parse.ts
  src/types/gitlog.d.ts
Labels: patch

#128 Fix custom labels not respected by the semver checker
  src/__tests__/github-release.test.ts
  src/github-release.ts
Labels: patch

#130 Changes the verbose logging so that it doesn't leak tokens
  src/github-release.ts
Labels: patch

#133 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: internal, skip-release

#134 Add artsy/reaction to the list of projects using auto
  README.md
Labels: documentation, skip-release

#136 Add Prior Art section to Readme
  README.md
Labels: documentation, skip-release

#137 Release v1.0.0
  package.json
Labels: major

#131 Tappable Auto - Plugin System
  docs/index.md
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/plugins.md
  package.json
  src/__tests__/git-changed-packages.test.ts
  src/__tests__/git.test.ts
  src/__tests__/github-release.test.ts
  src/__tests__/log-parse.test.ts
  src/cli/args.ts
  src/git.ts
  src/github-release.ts
  src/init.ts
  src/log-parse.ts
  src/main.ts
  src/plugins/npm/__tests__/package-config.test.ts
  src/plugins/npm/index.ts
  src/plugins/npm/package-config.ts
  src/utils/github-token.ts
  src/utils/logger.ts
  tsconfig.build.json
  yarn.lock
Labels: skip-release

#138 Flags all snake-case and autorc options all camelCase
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/getting-started.md
  src/cli/args.ts
  src/github-release.ts
  src/init.ts
  src/main.ts
Labels: major, skip-release

#139 Improve API Usage, Better Args Typing
  docs/pages/auto-init.md
  src/cli/args.ts
  src/main.ts
Labels: patch, skip-release

#144 Plugins Options: load official, npm package, or path
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/plugins.md
  src/cli/args.ts
  src/main.ts
  src/utils/__tests__/load-plugin.test.ts
  src/utils/__tests__/test-plugin.ts
  src/utils/load-plugins.ts
Labels: minor, skip-release

#149 Actually load plugins
  src/main.ts
  src/utils/load-plugins.ts
Labels: patch, skip-release

#150 Increase number of commits to scan for
  src/git.ts
  src/types/gitlog.d.ts
Labels: patch, skip-release

#151 Only set git user in CI env
  CHANGELOG.md
  package.json
  src/main.ts
  yarn.lock
Labels: minor, skip-release

#152 convert subcommand flags camelcase too
  src/cli/__tests__/args.test.ts
  src/cli/args.ts
Labels: patch, skip-release

#148 Ensure semVerLabels stays a map as expected
  .all-contributorsrc
  README.md
  src/main.ts
Labels: patch, skip-release

#146 Raise an error, and fail execution when a sub-command fails
  .all-contributorsrc
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/pages/plugins.md
  src/git.ts
  src/main.ts
  src/plugins/npm/index.ts
  src/utils/__tests__/exec-promise.test.ts
  src/utils/exec-promise.ts
Labels: patch

#154 A few missed "await exec" refactors
  src/__tests__/github-release.test.ts
  src/github-release.ts
Labels: patch

#157 Maintain context when spawning git process
  src/utils/exec-promise.ts
Labels: patch

#158 Ensure commit messages are strings
  src/__tests__/github-release.test.ts
  src/github-release.ts
  src/plugins/npm/index.ts
Labels: patch

#162 Await all hook promises
  src/main.ts
Labels: patch

#160 Only warn about git user when it isn't set
  CHANGELOG.md
  src/main.ts
Labels: patch

#165 Parse string authors
  package.json
  src/plugins/npm/index.ts
  src/types/parse-author.d.ts
  yarn.lock
Labels: minor

#167 Fix generating the changelog with custom labels
  src/__tests__/log-parse.test.ts
  src/github-release.ts
  src/log-parse.ts
Labels: patch

#171 When errors are caught fail the process
  src/__tests__/main.test.ts
  src/main.ts
Labels: patch

#174 String arg parse fail on null
  src/cli/__tests__/args.test.ts
  src/cli/args.ts
Labels: patch

#173 NPM Plugin: getPreviousVersion compare against published version
  package.json
  src/__tests__/main.test.ts
  src/github-release.ts
  src/plugins/npm/index.ts
  src/types/get-monorepo-packages.d.ts
  yarn.lock
Labels: minor

#179 add docs deploy note
  README.md
Labels: documentation, skip-release

#181 Switch to circleCI 2.1
  .circleci/config.yml
Labels: internal

#185 also log stdout on errors
  src/utils/exec-promise.ts
Labels: patch

#189 Pad color to be 6 digits long
  src/git.ts
Labels: patch

#182 Chrome Web Store Plugin
  docs/index.md
  docs/pages/chrome.md
  package.json
  src/github-release.ts
  src/main.ts
  src/plugins/chrome/index.ts
  src/utils/load-plugins.ts
  src/utils/make-hooks.ts
  yarn.lock
Labels: documentation, minor

#190 add shipit to docs
  docs/pages/plugins.md
  src/main.ts
  src/plugins/chrome/index.ts
  src/utils/make-hooks.ts
Labels: patch

#193 Fix github repo lookup
  src/__tests__/main.test.ts
  src/main.ts
Labels: patch

#192 Plugin Config
  docs/index.md
  docs/pages/chrome.md
  docs/pages/plugins.md
  docs/pages/writing-plugins.md
  src/github-release.ts
  src/main.ts
  src/plugins/chrome/index.ts
  src/utils/__tests__/load-plugin.test.ts
  src/utils/__tests__/test-plugin.ts
  src/utils/load-plugins.ts
Labels: documentation, minor

#197 `auto label`: must sort PRs first because they can get merged out of order
  src/__tests__/main.test.ts
  src/main.ts
Labels: patch

#199 correct help message for owner
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  src/cli/args.ts
Labels: documentation, patch

#200 release documentation only when files in `docs/` have changed
  scripts/publish-docs.sh
Labels: internal, skip-release

#205 NPM Plugin: if there is no published version default to package.json version
  src/plugins/npm/index.ts
Labels: patch

#207 NPM Plugin: to publish a scoped package `--access public` is needed
  src/plugins/npm/index.ts
Labels: patch

#209 fix rebased PRs
  package.json
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/__snapshots__/log-parse.test.ts.snap
  src/__tests__/git.test.ts
  src/__tests__/github-release.test.ts
  src/__tests__/log-parse.test.ts
  src/__tests__/make-commit-from-msg.ts
  src/git.ts
  src/github-release.ts
  src/log-parse.ts
  src/main.ts
  src/plugins/npm/__tests__/git-changed-packages.test.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/__tests__/exec-promise.test.ts
  src/utils/__tests__/load-plugin.test.ts
  src/utils/exec-promise.ts
  src/utils/load-plugins.ts
  yarn.lock
Labels: patch

#212 When there are no releases use first commit date for rebased PRs
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/git.test.ts
  src/__tests__/github-release.test.ts
  src/git.ts
  src/github-release.ts
Labels: patch

#213 Proper Error Catching
  src/plugins/npm/index.ts
Labels: documentation

#204 Pushes to master create changelog entry
  src/__tests__/__snapshots__/github-release.test.ts.snap
  src/__tests__/__snapshots__/log-parse.test.ts.snap
  src/__tests__/github-release.test.ts
  src/__tests__/log-parse.test.ts
  src/git.ts
  src/github-release.ts
  src/log-parse.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
Labels: minor

#214 fix test
  src/__tests__/__snapshots__/github-release.test.ts.snap
Labels: internal

#219 improve default label descriptions
  .all-contributorsrc
  README.md
  src/github-release.ts
Labels: patch

#225 add label description for `release` label back
  src/github-release.ts
Labels: patch

#226 Add dry-run flag for the rest of the commands
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  src/__tests__/__snapshots__/main.test.ts.snap
  src/cli/args.ts
  src/github-release.ts
  src/init.ts
  src/main.ts
Labels: minor

#227 load env vars from .env file
  docs/pages/getting-started.md
  package.json
  src/__tests__/main-env.test.ts
  src/main.ts
  yarn.lock
Labels: minor

#215 Shared Configuration
  docs/pages/autorc.md
  package.json
  src/__tests__/__snapshots__/main.test.ts.snap
  src/__tests__/main.test.ts
  src/main.ts
  src/utils/load-plugins.ts
  src/utils/try-require.ts
  yarn.lock
Labels: minor

#223 NPM Plugin: Inject NPM_TOKEN into `.npmrc` during `shipit`
  .circleci/config.yml
  docs/pages/circleci.md
  docs/pages/getting-started.md
  docs/pages/troubleshooting.md
  package.json
  src/__tests__/main.test.ts
  src/main.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/types/parse-author.d.ts
  src/types/set-npm-auth-token-for-ci.d.ts
  yarn.lock
Labels: minor

#233 test switching registry back
  .npmrc
Labels: patch

#234 add some comments to the code
  src/git.ts
  src/github-release.ts
  src/main.ts
Labels: internal, skip-release

#228 Rename onCreateLogParse to onCreateChangelog
  docs/pages/writing-plugins.md
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/__snapshots__/log-parse.test.ts.snap
  src/__tests__/changelog.test.ts
  src/__tests__/log-parse.test.ts
  src/changelog.ts
  src/github-release.ts
  src/log-parse.ts
  src/main.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/plugins/npm/index.ts
  src/utils/make-hooks.ts
Labels: major, skip-release

#235 Rename onCreateGitHubRelease to onCreateRelease
  docs/pages/writing-plugins.md
  src/__tests__/__snapshots__/auto-release.test.ts.snap
  src/__tests__/__snapshots__/release.test.ts.snap
  src/__tests__/auto-release-env.test.ts
  src/__tests__/auto-release.test.ts
  src/__tests__/changelog.test.ts
  src/__tests__/git.test.ts
  src/__tests__/main.test.ts
  src/__tests__/release.test.ts
  src/__tests__/semver.test.ts
  src/auto-release.ts
  src/changelog.ts
  src/cli/args.ts
  src/git.ts
  src/init.ts
  src/log-parse.ts
  src/main.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/release.ts
  src/semver.ts
  src/utils/make-hooks.ts
Labels: major, skip-release

#236 Update deps and move git class
  package.json
  src/__tests__/auto-release.test.ts
  src/__tests__/release.test.ts
  src/__tests__/semver.test.ts
  src/auto-release.ts
  src/changelog.ts
  src/cli/args.ts
  src/git.ts
  src/init.ts
  src/log-parse.ts
  src/plugins/chrome/index.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/__tests__/package-config.test.ts
  src/plugins/npm/index.ts
  src/release.ts
  src/semver.ts
  src/utils/__tests__/github-token.test.ts
  src/utils/__tests__/test-plugin.ts
  src/utils/exec-promise.ts
  src/utils/load-plugins.ts
  src/utils/slack.ts
  src/utils/try-require.ts
  tslint.json
  yarn.lock
Labels: internal, skip-release

#237 Rename package from `auto-release-cli` to `auto`
  .all-contributorsrc
  .circleci/config.yml
  README.md
  docs/home.md
  docs/pages/auto-changelog.md
  docs/pages/auto-comment.md
  docs/pages/auto-init.md
  docs/pages/auto-label.md
  docs/pages/auto-pr-check.md
  docs/pages/auto-pr.md
  docs/pages/auto-release.md
  docs/pages/auto-shipit.md
  docs/pages/auto-version.md
  docs/pages/autorc.md
  docs/pages/circleci.md
  docs/pages/getting-started.md
  docs/pages/introduction.md
  docs/pages/pr-interaction.md
  docs/pages/publishing.md
  docs/pages/troubleshooting.md
  docs/pages/writing-plugins.md
  package.json
  src/__tests__/__snapshots__/auto.test.ts.snap
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/auto-env.test.ts
  src/__tests__/auto.test.ts
  src/__tests__/changelog.test.ts
  src/auto-rc.json
  src/auto.ts
  src/cli/args.ts
  src/main.ts
  src/plugins/chrome/index.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/load-plugins.ts
  src/utils/make-hooks.ts
Labels: major

#239 Updates Octokit Usage
  package.json
  src/__tests__/git.test.ts
  src/git.ts
  yarn.lock
Labels: internal

#240 Fix `Push to Master` Changelog entries newline
  src/__tests__/changelog.test.ts
  src/__tests__/release.test.ts
  src/changelog.ts
Labels: patch

#241 test publishing docs
  scripts/publish-docs.sh
Labels: internal, skip-release

#242 Fix docs publishing
  docs/pages/chrome.md
  scripts/publish-docs.sh
Labels: internal, skip-release

#243 update contributor count
  README.md
Labels: internal, skip-release

#245 Pin parse-commit-message to v4.0.0
  package.json
  yarn.lock
Labels: patch

#246 Label Refactor: custom colors, descriptions, arbitrary labels, deprecate changelogTitles
  docs/pages/autorc.md
  package.json
  src/__tests__/__snapshots__/auto.test.ts.snap
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/auto.test.ts
  src/__tests__/changelog.test.ts
  src/__tests__/git.test.ts
  src/__tests__/release.test.ts
  src/__tests__/semver.test.ts
  src/auto.ts
  src/changelog.ts
  src/git.ts
  src/init.ts
  src/log-parse.ts
  src/plugins/conventional-commits/__tests__/conventional-commits.test.ts
  src/plugins/npm/__tests__/monorepo-log.test.ts
  src/release.ts
  yarn.lock
Labels: major, skip-release

#247 Split up `publish` hook into `version` and `publish`
  docs/pages/writing-plugins.md
  src/auto.ts
  src/plugins/chrome/index.ts
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
  src/utils/make-hooks.ts
Labels: major, skip-release

#248 add afterVersion and afterPublish hooks
  docs/pages/writing-plugins.md
  src/auto.ts
  src/utils/make-hooks.ts
Labels: minor

#249 afterShipit hook
  src/auto.ts
  src/release.ts
  src/utils/make-hooks.ts
Labels: minor

#250 released-label plugin
  docs/pages/plugins.md
  docs/pages/released-label.md
  package.json
  src/__tests__/git.test.ts
  src/git.ts
  src/plugins/released-label/__tests__/released-label.test.ts
  src/plugins/released-label/index.ts
  src/utils/load-plugins.ts
Labels: minor

#252 Released Plugin: lock merged issues
  docs/index.md
  docs/pages/released.md
  src/__tests__/git.test.ts
  src/git.ts
  src/plugins/released/index.ts
Labels: minor

#253 Released plugin: add released label to issue too
  docs/pages/released.md
  src/plugins/released/index.ts
Labels: minor

#255 Add clarity to a few of the docs
  docs/pages/autorc.md
  docs/pages/plugins.md
  docs/pages/released.md
Labels: documentation, skip-release

#257 Better config debug
  src/auto.ts
Labels: patch

#259 release plugin: do nothing when skip-release present
  src/plugins/released/__tests__/released-label.test.ts
  src/plugins/released/index.ts
Labels: patch

#260 load extends config from path
  src/__tests__/__snapshots__/auto.test.ts.snap
  src/__tests__/auto.test.ts
  src/auto.ts
Labels: patch

#261 remove .only
  src/__tests__/auto.test.ts
Labels: internal, skip-release

#262 Plugins and Configs: import from CWD
  package.json
  src/__tests__/auto.test.ts
  src/types/import-cwd.d.ts
  src/utils/__tests__/load-plugin.test.ts
  src/utils/try-require.ts
  yarn.lock
Labels: bug

#264 afterRelease hook
  docs/pages/writing-plugins.md
  src/auto.ts
  src/plugins/released/__tests__/released-label.test.ts
  src/plugins/released/index.ts
  src/utils/make-hooks.ts
Labels: minor

#265 add addLabel enterprise compat
  package.json
  src/__tests__/auto.test.ts
  src/__tests__/git.test.ts
  src/git.ts
  src/types/octokit-enterprise.d.ts
  yarn.lock
Labels: patch

#269 Custom labels still resolve changelog titles
  src/__tests__/__snapshots__/changelog.test.ts.snap
  src/__tests__/changelog.test.ts
  src/changelog.ts
Labels: bug

#270 modifyConfig hook
  docs/pages/writing-plugins.md
  src/__tests__/auto.test.ts
  src/__tests__/config.test.ts
  src/auto.ts
  src/config.ts
  src/plugins/released/index.ts
  src/utils/make-hooks.ts
Labels: minor

#272 `create-labels` update labels when the exist
  docs/pages/auto-init.md
  src/__tests__/git.test.ts
  src/__tests__/release.test.ts
  src/cli/args.ts
  src/git.ts
  src/release.ts
Labels: minor

#274 can't warn here or else `version` will fail
  src/plugins/npm/index.ts
Labels: patch

#276 add more logging for lerna debugging
  src/auto.ts
  src/plugins/npm/index.ts
Labels: patch

#277 run git status in verbose mode for lerna
  src/plugins/npm/index.ts
Labels: patch

#279 ensure that setRcToken is respected
  src/plugins/npm/__tests__/npm.test.ts
  src/plugins/npm/index.ts
Labels: patch
