Repository intuit/auto, pull requests merged in 2020-07, with the labels that each got.

#1339 fix: command example for pr-status
  packages/cli/src/parse-args.ts
Labels: documentation

#1341 log full error
  packages/cli/src/run.ts
Labels: patch

#1342 add docsearch
  docs/css/syntax-highlighting-overrides.css
  docs/pages/_app.js
  docs/pages/_document.js
Labels: documentation

#1343 update ignite
  package.json
  yarn.lock
Labels: documentation

#1344 fix search breaking on nav
  docs/pages/_app.js
Labels: documentation

#1345 docs: fix mobile search
  docs/css/syntax-highlighting-overrides.css
  package.json
  yarn.lock
Labels: documentation

#1346 update ignite
  package.json
  yarn.lock
Labels: documentation

#1347 fix docs dark mode
  package.json
  yarn.lock
Labels: documentation

#1348 don't generate docs for node_modules
  docs/generate-command-docs.js
Labels: documentation

#1350 Enable easier "all-contributors" usage on non-javascript project + add extra contributors to changelogs
  .all-contributorsrc
  README.md
  packages/core/src/auto.ts
  plugins/all-contributors/README.md
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/package.json
  plugins/all-contributors/src/index.ts
  typings/all-contributors.d.ts
Labels: minor

#1349 attempt to construct the GitHub graphql root API endpoint if githubApi is provided
  docs/pages/docs/configuration/autorc.mdx
  packages/core/src/__tests__/git.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1362 add --to flag to "auto release"
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#1361 npm: find available canary version
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1363 fix: prioritize base branch head ref
  packages/core/src/auto.ts
Labels: patch

#1364 update contributor count
  README.md
Labels: documentation

#1368 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#1369 exit in CI when no valid git email + name found
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1370 add .autorc "author" option that combines email + name
  docs/pages/docs/configuration/autorc.mdx
  docs/pages/docs/configuration/non-npm.mdx
  packages/cli/__tests__/main.test.ts
  packages/core/package.json
  packages/core/src/__tests__/auto-git-user-in-ci.test.ts
  packages/core/src/auto.ts
  packages/core/src/types.ts
Labels: minor

#1371 allow default SEMVER label to be configured
  docs/pages/docs/configuration/autorc.mdx
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/__tests__/config.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/match-sha-to-pr.ts
  packages/core/src/release.ts
  packages/core/src/semver.ts
  packages/core/src/types.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/slack/__tests__/slack.test.ts
Labels: minor

#1382 push prerelease branch in addition to tags
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1383 Add `--exists $LABEL` to label command
  docs/pages/blog/using-shipit.mdx
  docs/pages/docs/extras/label.md
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#1393 Fixes baseBranch from config
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1395 fix Chrome manifest copy to build folder
  plugins/chrome/src/index.ts
Labels: patch

#1397 skip publish for private npm packages
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/__tests__/set-npm-token.test.ts
  plugins/npm/src/index.ts
  plugins/npm/src/set-npm-token.ts
  plugins/npm/src/utils.ts
Labels: minor

#1399 add error message around mistmatched auto versions
  packages/cli/src/run.ts
Labels: patch

#1402 catch errors when finding tags on next
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1410 add helpful error message when git state isn't clean for gh-pages plugin
  plugins/gh-pages/README.md
  plugins/gh-pages/package.json
  plugins/gh-pages/src/index.ts
Labels: patch

#1409 Stream logs in verbose mode
  packages/core/src/utils/exec-promise.ts
Labels: patch

#1414 add Github Package Registry docs
  docs/pages/docs/build-platforms/github-actions.mdx
  plugins/conventional-commits/src/index.ts
Labels: documentation

#1412 respect registry set at top level for lerna
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/__tests__/set-npm-token.test.ts
  plugins/npm/src/index.ts
  plugins/npm/src/set-npm-token.ts
Labels: patch

#1413 Implement full maven release workflow
  plugins/maven/__tests__/maven.test.ts
  plugins/maven/src/index.ts
  plugins/maven/src/maven.ts
  plugins/maven/src/native-version-update.ts
Labels: minor

#1419 don't leak GH_TOKEN in exec promise output
  packages/core/src/auto.ts
  packages/core/src/utils/__tests__/exec-promise.test.ts
  packages/core/src/utils/exec-promise.ts
Labels: patch

#1420 add docs about running lengthy builds during publish
  docs/pages/docs/welcome/quick-merge.mdx
  plugins/npm/README.md
Labels: documentation

#1421 update ignite
  package.json
  yarn.lock
Labels: dependencies

#1427 don't prefix tags in lerna independent mode
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1424 Fix various rate limiting issues
  packages/cli/__tests__/main.test.ts
  packages/core/package.json
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/release.ts
  plugins/first-time-contributor/src/index.ts
  plugins/released/src/index.ts
  yarn.lock
Labels: patch
