Repository intuit/auto, pull requests merged in 2020-04, with the labels that each got.

#1097 add link in released comment + handle multiple releases
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
  yarn.lock
Labels: patch

#1099 Add Brew Plugin
  README.md
  docs/index.md
  formula-template.rb
  package.json
  packages/core/src/__tests__/__snapshots__/validate-config.test.ts.snap
  packages/core/src/__tests__/validate-config.test.ts
  packages/core/src/validate-config.ts
  plugins/brew/README.md
  plugins/brew/__tests__/__snapshots__/brew.test.ts.snap
  plugins/brew/__tests__/brew.test.ts
  plugins/brew/package.json
  plugins/brew/src/index.ts
  plugins/brew/tsconfig.json
  tsconfig.dev.json
Labels: minor

#1100 fix default formula path
  plugins/brew/src/index.ts
Labels: patch

#1101 fix docs syntax highlighting
  plugins/brew/README.md
Labels: documentation

#1104 next: add whitspace so markdown formats correctly
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/auto.ts
Labels: patch

#1103 Add `--list-plugins` flag to `info` command
  docs/pages/non-npm.md
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/init.ts
  packages/core/src/utils/__tests__/__snapshots__/load-plugin.test.ts.snap
  packages/core/src/utils/__tests__/load-plugin-canary.test.ts
  packages/core/src/utils/__tests__/load-plugin-windows.test.ts
  packages/core/src/utils/__tests__/load-plugin.test.ts
  packages/core/src/utils/load-plugins.ts
Labels: minor

#1108 shipit: expose --only-publish-with-release-label
  packages/cli/src/parse-args.ts
  packages/core/src/semver.ts
  packages/core/src/utils/load-plugins.ts
Labels: minor

#1110 Fix info command in fresh envs + list plugins in binary
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/auto.ts
  packages/core/src/utils/is-binary.ts
  packages/core/src/utils/load-plugins.ts
Labels: patch, released

#1111 Changelog bugs
  packages/core/src/__tests__/__snapshots__/match-sha-to-pr.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/release.test.ts
  packages/core/src/match-sha-to-pr.ts
  packages/core/src/release.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1112 Turn on eslint rules that would have prevented last bug
  .eslintrc
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/init.ts
  packages/core/src/release.ts
  packages/core/src/utils/exec-promise.ts
  packages/core/src/validate-config.ts
  plugins/cocoapods/src/index.ts
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/gradle/src/index.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/released/src/index.ts
  plugins/slack/src/index.ts
Labels: internal

#1114 --dry-run improvements
  packages/core/src/auto.ts
Labels: patch

#1115 include first commit in changelogs
  packages/core/src/__tests__/__snapshots__/git.test.ts.snap
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
Labels: patch

#1117 Add most flags for version+changelog+release to shipit/latest
  packages/cli/src/parse-args.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#1120 Cocoapods -> CocoaPods
  plugins/cocoapods/README.md
Labels: documentation

#1121 fix: push to master w/--only-publish-with-release-label creating release
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/semver.ts
Labels: patch

#1123 ensure commits pushed directly to next branch are labelled correctly in next-PR changelog
  packages/core/src/__tests__/__snapshots__/match-sha-to-pr.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/release.test.ts
  packages/core/src/changelog.ts
  packages/core/src/match-sha-to-pr.ts
  packages/core/src/release.ts
Labels: patch

#1132 Improve next branch preview changelog
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1133 pr-check: succeed on pre-release branch PRs
  packages/core/src/auto.ts
Labels: patch

#1134 fix creating canary with no Latest Release
  packages/core/src/__tests__/determine-next-version.test.ts
  packages/core/src/auto.ts
Labels: patch

#1135 Next improvements
  docs/pages/build-platforms/travis.md
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/git.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/release.ts
  typings/gitlog.d.ts
  yarn.lock
Labels: patch

#1136 Skip next commit hooks
  packages/core/src/auto.ts
  plugins/npm/src/index.ts
Labels: patch

#1137 Fix omitting merges from master into next when running "shipit"
  packages/core/src/auto.ts
  packages/core/src/release.ts
Labels: patch

#1148 all contributors: add ability to add non-code contributions
  plugins/all-contributors/README.md
  plugins/all-contributors/__tests__/__snapshots__/all-contributors.test.ts.snap
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: minor

#1149 first-time-contributor: cache results of graphql queries
  plugins/first-time-contributor/src/index.ts
Labels: patch

#1150 Add renovate-pro[bot] to bot list
  packages/bot-list/src/index.ts
Labels: patch

#1152 upload-assets: update deprecated option
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  plugins/upload-assets/src/index.ts
Labels: patch

#1155 Add --quiet flag
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/utils/git-reset.ts
  packages/core/src/utils/logger.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1159 add verbose logs when branch is behind
  packages/core/src/auto.ts
Labels: patch

#1160 bug in silent flag
  plugins/npm/src/index.ts
Labels: patch

#1161 fix quiet flag in npm plugin. was always on
  plugins/npm/src/index.ts
Labels: patch

#1170 set noVersionPrefix if tagVersionPrefix is set
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1171 Include Chrome manifest in build folder + ensure correct version is used
  plugins/chrome/src/index.ts
Labels: minor

#1172 actually fix docs publish
  docs/generate-command-docs.js
Labels: documentation

#1174 --silent is not a lerna flag
  plugins/npm/src/index.ts
Labels: patch

#1184 pass Gradle options to getProperties helper function
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
Labels: patch
