Repository intuit/auto, pull requests merged in 2020-08, with the labels that each got.

#1429 Fix lerna independent "next" releases
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/validate-config.test.ts
  packages/core/src/auto.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1437 Make non-npm docs clearer
  docs/pages/_document.js
  docs/pages/docs/configuration/non-npm.mdx
Labels: documentation

#1438 anonimize IPs for analytics
  docs/pages/_document.js
Labels: documentation

#1439 upgrade ignite for purgeCSS
  package.json
  yarn.lock
Labels: documentation

#1442 upgrade eslint + ensure all imported packages are in package.json
  .eslintrc
  package.json
  packages/cli/__tests__/main.test.ts
  packages/cli/src/bin/auto.ts
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/package.json
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-comment.test.ts
  packages/core/src/__tests__/auto-env.test.ts
  packages/core/src/__tests__/auto-git-user-in-ci.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/get-remote.test.ts
  packages/core/src/__tests__/major-version-branches.test.ts
  packages/core/src/__tests__/remote.test.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/config.ts
  packages/core/src/git.ts
  packages/core/src/init.ts
  packages/core/src/plugins/__tests__/filter-non-pull-request.test.ts
  packages/core/src/release.ts
  packages/core/src/utils/__tests__/test-plugin.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/logger.ts
  packages/core/src/utils/try-require.ts
  plugins/all-contributors/package.json
  plugins/exec/package.json
  plugins/first-time-contributor/package.json
  plugins/first-time-contributor/src/index.ts
  plugins/git-tag/src/index.ts
  plugins/gradle/package.json
  plugins/jira/package.json
  plugins/maven/package.json
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/released/package.json
  plugins/s3/package.json
  plugins/upload-assets/src/index.ts
  yarn.lock
Labels: patch

#1444 Revert "Merge pull request #1439 from intuit/docss"
  package.json
  yarn.lock
Labels: documentation

#1445 Fix Independent `next` versioning
  packages/core/src/auto.ts
  packages/core/src/git.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1446 fix: use GH_TOKEN if PRIVATE_TOKEN is not set
  plugins/all-contributors/src/index.ts
Labels: minor

#1447 improve jenkins docs
  docs/pages/docs/build-platforms/jenkins.mdx
Labels: documentation

#1450 publish auto with 'exact' versioning
  package.json
Labels: patch

#1460 Fix finding available canary version and add logging
  plugins/npm/src/index.ts
Labels: patch

#1465 Improve package manager plugin docs
  docs/pages/docs/_sidebar.mdx
  docs/pages/docs/configuration/plugins.mdx
  plugins/chrome/README.md
  plugins/cocoapods/README.md
  plugins/crates/README.md
  plugins/gem/README.md
  plugins/git-tag/README.md
  plugins/gradle/README.md
  plugins/maven/README.md
  plugins/npm/README.md
Labels: documentation

#1466 correct enterprise upload assets baseUrl
  packages/core/package.json
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/src/index.ts
  yarn.lock
Labels: patch

#1467 🤖 don't thank any of the bots in bot-list
  plugins/first-time-contributor/package.json
  plugins/first-time-contributor/src/index.ts
Labels: patch

#1468 don't set baseUrl for public asset upload
  plugins/upload-assets/src/index.ts
Labels: patch

#1472 correct behavior for lerna project with private packages
  packages/core/src/utils/get-lerna-packages.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1473 Fix label initialization
  packages/core/src/init.ts
Labels: patch

#1475 fix some links in docs
  docs/pages/docs/configuration/non-npm.mdx
  docs/plugins/home.js
  formula-template.rb
Labels: documentation

#1474 only post partial release notes to next releases
  packages/core/src/auto.ts
Labels: patch

#1476 Fix adding multiple contributors at once
  plugins/all-contributors/src/index.ts
Labels: patch

#1487 feat: option to specify a different command to use for pod
  plugins/cocoapods/README.md
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: minor
