Repository intuit/auto, pull requests merged in 2020-03, with the labels that each got.

#998 Config Validation + Command Defaults
  docs/generate-command-docs.js
  docs/pages/autorc.md
  docs/pages/plugins.md
  docs/pages/troubleshooting.md
  docs/pages/writing-plugins.md
  package.json
  packages/cli/__tests__/main.test.ts
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/__snapshots__/validate-config.test.ts.snap
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-comment.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/validate-config.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/init.ts
  packages/core/src/release.ts
  packages/core/src/types.ts
  packages/core/src/utils/make-hooks.ts
  packages/core/src/utils/omit.ts
  packages/core/src/validate-config.ts
  plugins/all-contributors/package.json
  plugins/all-contributors/src/index.ts
  plugins/chrome/package.json
  plugins/chrome/src/index.ts
  plugins/conventional-commits/src/index.ts
  plugins/crates/src/index.ts
  plugins/git-tag/src/index.ts
  plugins/gradle/src/index.ts
  plugins/jira/package.json
  plugins/jira/src/index.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/npm/README.md
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
  plugins/omit-commits/package.json
  plugins/omit-commits/src/index.ts
  plugins/omit-release-notes/package.json
  plugins/omit-release-notes/src/index.ts
  plugins/released/package.json
  plugins/released/src/index.ts
  plugins/s3/package.json
  plugins/s3/src/index.ts
  plugins/slack/package.json
  plugins/slack/src/index.ts
  plugins/twitter/package.json
  plugins/twitter/src/index.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
  tsconfig.json
  typings/fromentries.d.ts
  yarn.lock
Labels: minor

#1000 Default Config When running shipit
  packages/cli/src/run.ts
  packages/core/src/auto.ts
Labels: patch

#1001 Respect PR label when conventional commit message is present
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/src/index.ts
Labels: patch

#1012 don't force publish canary/next for independent lerna projects
  packages/core/src/auto.ts
  plugins/npm/__tests__/__snapshots__/npm.test.ts.snap
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1013 fix "Push to master" on next branch
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/utils/get-current-branch.ts
Labels: patch

#1015 info: handle when there is no previous version
  packages/core/src/auto.ts
Labels: patch

#1016 add license to all sub-packages
  package.json
  packages/cli/README.md
  packages/core/package.json
  plugins/all-contributors/package.json
  plugins/chrome/package.json
  plugins/conventional-commits/package.json
  plugins/crates/package.json
  plugins/first-time-contributor/package.json
  plugins/git-tag/package.json
  plugins/gradle/package.json
  plugins/jira/package.json
  plugins/maven/package.json
  plugins/npm/package.json
  plugins/omit-commits/package.json
  plugins/omit-release-notes/package.json
  plugins/released/package.json
  plugins/s3/package.json
  plugins/slack/package.json
  plugins/twitter/package.json
  plugins/upload-assets/package.json
  scripts/template-plugin/package.json
Labels: patch

#1017 set license on CLI
  packages/cli/package.json
Labels: patch

#1019 test for ancestor in windows friendly way
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
Labels: patch

#1021 Fix loading canary versions of official plugins
  packages/core/src/utils/__tests__/load-plugin-canary.test.ts
  packages/core/src/utils/load-plugins.ts
Labels: patch

#1022 fix plugin loading from absolute windows paths
  packages/core/src/utils/__tests__/load-plugin-windows.test.ts
  packages/core/src/utils/load-plugins.ts
Labels: patch

#1018 determine if branch behind remote and exit before trying to publish
  docs/pages/quick-merge.md
  packages/cli/README.md
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  plugins/git-tag/src/index.ts
Labels: minor

#1024 fix tests
  packages/core/src/__tests__/auto.test.ts
Labels: internal, released

#1025 npm: respect subPackageChangelogs false
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch, released

#1026 Changelog formatting
  CHANGELOG.md
  packages/cli/CHANGELOG.md
  packages/core/CHANGELOG.md
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/__tests__/config.test.ts
  packages/core/src/changelog.ts
  packages/core/src/release.ts
  plugins/all-contributors/CHANGELOG.md
  plugins/chrome/CHANGELOG.md
  plugins/conventional-commits/CHANGELOG.md
  plugins/crates/CHANGELOG.md
  plugins/first-time-contributor/CHANGELOG.md
  plugins/git-tag/CHANGELOG.md
  plugins/gradle/CHANGELOG.md
  plugins/jira/CHANGELOG.md
  plugins/jira/__tests__/__snapshots__/jira.test.ts.snap
  plugins/maven/CHANGELOG.md
  plugins/npm/CHANGELOG.md
  plugins/npm/__tests__/__snapshots__/monorepo-log.test.ts.snap
  plugins/omit-commits/CHANGELOG.md
  plugins/omit-release-notes/CHANGELOG.md
  plugins/released/CHANGELOG.md
  plugins/s3/CHANGELOG.md
  plugins/slack/CHANGELOG.md
  plugins/twitter/CHANGELOG.md
  plugins/upload-assets/CHANGELOG.md
Labels: patch, released

#1028 Make gitlog include merge commit files
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/git.test.ts.snap
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
  typings/gitlog.d.ts
  yarn.lock
Labels: patch

#1032 "version" would be wrong with label-less PRs + 'none' release types
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/semver.ts
Labels: patch

#1031 Add GitHub Pages Plugin
  .circleci/config.yml
  README.md
  docs/index.md
  package.json
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  packages/core/src/utils/__tests__/verify-auth.test.ts
  packages/core/src/utils/verify-auth.ts
  plugins/gh-pages/README.md
  plugins/gh-pages/__tests__/gh-pages.test.ts
  plugins/gh-pages/package.json
  plugins/gh-pages/src/index.ts
  plugins/gh-pages/tsconfig.json
  scripts/create-plugin.js
  scripts/publish-docs.sh
  scripts/template-plugin/src/index.ts
  tsconfig.dev.json
  yarn.lock
Labels: minor

#1029 📦 🐈 Yarn 2 Compatibility
  docs/pages/getting-started.md
  packages/cli/src/bin/auto.ts
  packages/core/package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/config.test.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/utils/__tests__/load-plugin.test.ts
  packages/core/src/utils/__tests__/test.js
  packages/core/src/utils/__tests__/try-require.test.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/try-require.ts
  plugins/first-time-contributor/package.json
Labels: patch

#1033 Add Exec Plugin
  packages/core/src/auto.ts
  packages/core/src/config.ts
  plugins/exec/README.md
  plugins/exec/__tests__/__snapshots__/exec.test.ts.snap
  plugins/exec/__tests__/exec.test.ts
  plugins/exec/package.json
  plugins/exec/src/index.ts
  plugins/exec/tsconfig.json
  plugins/omit-commits/README.md
  tsconfig.dev.json
Labels: minor

#996 🐘 Gradle Plugin: Add support for snapshot versioning, publishing, and less configuration
  README.md
  docs/pages/autorc.md
  lerna.json
  package.json
  packages/cli/README.md
  packages/core/src/__tests__/auto-comment.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/changelog.test.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/gradle/README.md
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/package.json
  plugins/gradle/src/index.ts
  typings/fromentries.d.ts
  yarn.lock
Labels: minor

#1036 Better GitHub Actions support + docs for github action + handle GITHUB_TOKEN
  docs/pages/build-platforms/github-actions.md
  packages/cli/src/run.ts
  packages/core/src/__tests__/get-remote.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1037 Update github-actions.md to match actions/checkout@v2
  docs/pages/build-platforms/github-actions.md
Labels: documentation

#1038 When checking if remote commits ignore git error message
  packages/core/src/auto.ts
Labels: patch

#1039 try credentialed remotes first
  packages/core/src/__tests__/remote.test.ts
  packages/core/src/auto.ts
Labels: patch

#1051 add exec plugin to docs
  README.md
  docs/index.md
  plugins/exec/README.md
Labels: documentation

#1052 Only trim exec output if its a string
  plugins/exec/src/index.ts
Labels: patch

#1056 Update jenkins.md
  docs/pages/build-platforms/jenkins.md
Labels: documentation

#1057 refresh home page
  docs/home.md
  docs/plugins/add-label.png
  docs/plugins/changelog-example.png
  docs/plugins/home.js
  docs/plugins/merge.png
  docs/plugins/open-pr.png
  docs/plugins/release.png
  docs/plugins/tailwind.plugin.css
  package.json
  yarn.lock
Labels: documentation

#1058 Update github-actions.md
  docs/pages/build-platforms/github-actions.md
Labels: documentation

#1059 fix homepage images
  docs/plugins/home.js
Labels: documentation

#1060 Fix some docs bugs
  docs/pages/getting-started.md
  docs/pages/introduction.md
  docs/plugins/home.js
  package.json
  yarn.lock
Labels: documentation

#1061 grammer
  docs/plugins/home.js
Labels: documentation

#1066 Cocoapods plugin
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/auto.ts
  plugins/cocoapods/README.md
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/package.json
  plugins/cocoapods/src/index.ts
  plugins/cocoapods/src/utilities.ts
  plugins/cocoapods/tsconfig.json
  tsconfig.dev.json
  yarn.lock
Labels: minor

#1068 add Cocoapod to docs
  README.md
  docs/index.md
Labels: documentation

#1070 All contributors bug
  .all-contributorsrc
  README.md
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: patch

#1067 Re-introduce `build` option back, but make it configurable so that
  plugins/gradle/README.md
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
Labels: minor

#1083 always use tag version for release title, prevent using annotation
  packages/core/src/git.ts
Labels: patch

#1084 Add --title flag to 'auto changelog'
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#1085 Exit with warning when canary or next is unimplemented
  packages/core/src/auto.ts
Labels: patch

#1086 fix(conventional-commits): skip release when no increment detected
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/src/index.ts
Labels: patch
