Repository intuit/auto, pull requests merged in 2020-11, with the labels that each got.

#1590 feat: add ssh support for connecting to github
  packages/core/src/__tests__/get-remote.test.ts
  packages/core/src/auto.ts
Labels: minor

#1629 Fix non-ssh release
  packages/core/src/utils/verify-auth.ts
Labels: patch

#1630 add "commitNextVersion" option to NPM plugin
  plugins/npm/README.md
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1631 NPM: independent next releases update dependency versions
  .eslintrc
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1633 handle multiple spaces in "lerna changed" output
  plugins/npm/src/index.ts
Labels: patch

#1632 add timeout when verifying auth to remote
  package.json
  packages/cli/__tests__/main.test.ts
  packages/core/src/utils/__tests__/verify-auth.test.ts
  packages/core/src/utils/verify-auth.ts
Labels: patch

#1636 improve pr-check usage + don't fail on runs in CI base branch
  .circleci/config.yml
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto-ci-base-branch.test.ts
  packages/core/src/auto.ts
Labels: patch

#1637 Don't add release comment to PRs created by bots
  plugins/released/README.md
  plugins/released/__tests__/released-label.test.ts
  plugins/released/package.json
  plugins/released/src/index.ts
Labels: minor

#1650 add dry-run info to afterShipIt hook
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  packages/core/src/auto.ts
  plugins/gradle/src/index.ts
  plugins/maven/src/index.ts
Labels: minor

#1662 Improve readability of release notes
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/changelog.ts
Labels: patch

#1663 fix url pr-check uses for auto's CI
  .circleci/config.yml
Labels: internal

#1664 Improve release notes section rendering in npm monorepos
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/changelog.ts
Labels: patch

#1666 fix blog links
  package.json
  yarn.lock
Labels: documentation
