Repository intuit/auto, pull requests merged in 2020-06, with the labels that each got.

#1271 chore: accurately name variable within inOldVersionBranch()
  packages/core/src/auto.ts
Labels: internal

#1273 fix next release start commit calculation when tags are package@version
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
Labels: patch

#1275 if canary --force provided default to patch
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1277 check for autoPublishRepo before trying to add it
  plugins/cocoapods/README.md
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: minor

#1278 fix automated old branch creation
  packages/core/src/__tests__/major-version-branches.test.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
Labels: patch

#1296 better docs theming
  docs/pages/_document.js
  docs/plugins/home.js
  package.json
  yarn.lock
Labels: documentation

#1297 add logos and frontmatters to docs
  docs/generate-command-docs.js
  docs/pages/docs/build-platforms/circleci.mdx
  docs/pages/docs/build-platforms/github-actions.mdx
  docs/pages/docs/build-platforms/jenkins.mdx
  docs/pages/docs/build-platforms/travis.mdx
  docs/pages/docs/configuration/autorc.mdx
  docs/pages/docs/configuration/non-npm.mdx
  docs/pages/docs/configuration/plugins.mdx
  docs/pages/docs/configuration/troubleshooting.mdx
  docs/pages/docs/extras/changelog.md
  docs/pages/docs/extras/create-labels.md
  docs/pages/docs/index.mdx
  docs/pages/docs/plugins/changelog-hooks.mdx
  docs/pages/docs/plugins/configuration-hooks.mdx
  docs/pages/docs/plugins/hook-api-docs.mdx
  docs/pages/docs/plugins/init-hooks.mdx
  docs/pages/docs/plugins/log-parse-hooks.mdx
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  docs/pages/docs/plugins/writing-plugins.mdx
  docs/pages/docs/plugins/writing-publishing-plugins.mdx
  docs/pages/docs/pr-interaction.mdx
  docs/pages/docs/welcome/getting-started.mdx
  docs/pages/docs/welcome/quick-merge.mdx
  docs/plugins/home.js
  docs/public/dark-logo-large.png
  docs/public/dark-logo-small.png
  docs/public/light-logo-large.png
  docs/public/light-logo-small.png
  docs/public/logo-dark.png
  docs/public/logo.gif
  docs/public/logo.png
  docs/public/monochrome-logo-large.png
  docs/public/monochrome-logo-small.png
  package.json
  yarn.lock
Labels: documentation

#1298 docs design review
  README.md
  docs/css/syntax-highlighting-overrides.css
  docs/generate-command-docs.js
  docs/pages/docs/configuration/autorc.mdx
  docs/pages/docs/configuration/plugins.mdx
  docs/pages/docs/index.mdx
  docs/public/readme-logo.png
  package.json
  plugins/cocoapods/README.md
  plugins/exec/README.md
  plugins/gradle/README.md
  plugins/omit-commits/README.md
  yarn.lock
Labels: documentation

#1299 Fix images in docs
  docs/plugins/home.js
  package.json
  yarn.lock
Labels: documentation

#1300 add image lightboxes and fix some bugs in ignite
  docs/pages/_app.js
  package.json
  yarn.lock
Labels: documentation

#1302 fix blog
  package.json
  yarn.lock
Labels: documentation

#1308 fix home page icons first load
  docs/pages/_app.js
  docs/pages/_document.js
  docs/pages/docs/_sidebar.mdx
  docs/plugins/home.js
Labels: documentation

#1295 Remove maven release plugin requirement
  package.json
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/exec/__tests__/exec.test.ts
  plugins/maven/README.md
  plugins/maven/__tests__/maven.test.ts
  plugins/maven/package.json
  plugins/maven/src/index.ts
  plugins/s3/__tests__/s3.test.ts
  tsconfig.json
  yarn.lock
Labels: minor

#1318 fix curl version update
  scripts/auto-update-curl-version.js
Labels: patch

#1315 Update makeRelease to support 'from' and 'useVersion' options with build part of semver
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1320 stop parsing release notes when we hit an automated comment created by auto
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/changelog.ts
  packages/core/src/git.ts
Labels: patch

#1325 upgrade next-ignite - adds page titles and favicon
  docs/public/auto.gif
  docs/public/changelog.png
  docs/public/comment.png
  docs/public/pr.png
  docs/public/release.png
  docs/public/shipit.png
  docs/public/version.png
  package.json
  yarn.lock
Labels: documentation

#1324 standardize default label colors
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/config.test.ts
  packages/core/src/release.ts
Labels: patch

#1326 fix flash of unstyled paragraph + add title to home page
  docs/plugins/home.js
Labels: documentation

#1327 add dark mode favicon
  docs/public/favicon-dark.png
  docs/public/favicon.png
  package.json
  yarn.lock
Labels: documentation

#1328 better dark mode
  docs/public/attach-dark-mode.js
  package.json
  yarn.lock
Labels: documentation

#1334 Updates afterRelease documented parameters
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
Labels: documentation

#1336 Fix docs links
  docs/pages/blog/v8.mdx
  docs/pages/docs/configuration/non-npm.mdx
  docs/pages/docs/configuration/plugins.mdx
  docs/pages/docs/extras/changelog.md
  docs/pages/docs/extras/release.md
  docs/pages/docs/extras/shipit.md
  docs/pages/docs/extras/version.md
  docs/pages/docs/index.mdx
  docs/pages/docs/plugins/changelog-hooks.mdx
  docs/pages/docs/plugins/configuration-hooks.mdx
  docs/pages/docs/plugins/hook-api-docs.mdx
  docs/pages/docs/plugins/writing-plugins.mdx
  docs/pages/docs/plugins/writing-publishing-plugins.mdx
  docs/pages/docs/welcome/getting-started.mdx
  docs/plugins/get-started-button.js
  docs/plugins/home.js
  plugins/exec/README.md
Labels: documentation

#1337 update ignite + fix open in new tab
  package.json
  yarn.lock
Labels: documentation

#1338 update ignite
  package.json
  yarn.lock
Labels: documentation
