Repository intuit/auto, pull requests merged in 2020-05, with the labels that each got.

#1188 fix npm canary release w/o any tags
  packages/core/src/utils/exec-promise.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
Labels: patch

#1191 Fix PR detection bug
  packages/core/src/auto.ts
Labels: patch

#1193 add --no-changelog option
  docs/generate-command-docs.js
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
Labels: minor

#1194 Add log when exiting early on independent lerna projects
  plugins/npm/src/index.ts
Labels: patch

#1205 fix(docs): mention correct key within forcePublish
  plugins/npm/README.md
Labels: documentation

#1207 fix(auto): correct git porcelain error message
  packages/core/src/auto.ts
Labels: patch

#1210 Slack Plugin HTTP Proxy support
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/package.json
  plugins/slack/src/index.ts
  yarn.lock
Labels: minor

#1212 Increase gitlog maximum buffer size to Infinity
  packages/core/src/git.ts
Labels: patch

#1215 pass exact flag to publish too
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1216 only create sub-package changelogs for `lerna changed` packages
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1218 Improve Plugin Docs
  docs/index.md
  docs/pages/plugins/changelog-hooks.md
  docs/pages/plugins/configuration-hooks.md
  docs/pages/plugins/hook-api-docs.md
  docs/pages/plugins/init-hooks.md
  docs/pages/plugins/log-parse-hooks.md
  docs/pages/plugins/release-lifecycle-hooks.md
  docs/pages/plugins/writing-plugins.md
  docs/pages/plugins/writing-publishing-plugins.md
  scripts/update-tap.js
Labels: documentation

#1219 fix links in plugin docs
  docs/pages/plugins/hook-api-docs.md
  docs/pages/plugins/writing-plugins.md
  docs/pages/plugins/writing-publishing-plugins.md
  docs/pages/writing-plugins.md
Labels: documentation

#1220 clean up writing plugin docs
  docs/pages/plugins/configuration-hooks.md
  docs/pages/plugins/hook-api-docs.md
  docs/pages/plugins/writing-plugins.md
  docs/pages/plugins/writing-publishing-plugins.md
Labels: documentation

#1221 remove dead link in docs
  docs/pages/plugins/hook-api-docs.md
  docs/pages/plugins/release-lifecycle-hooks.md
Labels: documentation

#1223 fix(shipit): correct variable name isBaseBranch
  packages/core/src/auto.ts
Labels: internal

#1225 align octokit types
  packages/cli/package.json
  yarn.lock
Labels: patch

#1227 fix upload-assets plugin
  plugins/upload-assets/src/index.ts
Labels: patch

#1226 add test that ensure bundled auto still works
  packages/cli/__tests__/__snapshots__/bundle.test.ts.snap
  packages/cli/__tests__/bundle.test.ts
Labels: internal

#1235 allow more rc file types
  docs/pages/autorc.md
  packages/core/src/config.ts
Labels: minor

#1236 sub-package changelogs: Handle when no changes made to monorepo packages
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1241 Maven plugin support for configurable SNAPSHOT branch
  plugins/maven/README.md
  plugins/maven/src/index.ts
Labels: minor

#1243 fallback to tag name when the release has no name
  plugins/released/src/index.ts
  plugins/slack/src/index.ts
Labels: patch

#1244 automatically update install version in docs
  docs/pages/non-npm.md
  docs/update-curl-version.js
  package.json
Labels: documentation

#1206 Extend default labels
  docs/pages/autorc.md
  package.json
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/changelog.ts
  packages/core/src/release.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/slack/__tests__/slack.test.ts
  yarn.lock
Labels: patch

#1246 Changelog formatting
  CHANGELOG.md
  packages/bot-list/CHANGELOG.md
  packages/core/CHANGELOG.md
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/__snapshots__/log-parse.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/log-parse.test.ts
  packages/core/src/changelog.ts
  packages/core/src/log-parse.ts
  packages/core/src/release.ts
  plugins/all-contributors/CHANGELOG.md
  plugins/brew/CHANGELOG.md
  plugins/first-time-contributor/CHANGELOG.md
  plugins/gem/CHANGELOG.md
  plugins/git-tag/CHANGELOG.md
  plugins/npm/CHANGELOG.md
  plugins/released/CHANGELOG.md
  plugins/slack/CHANGELOG.md
  plugins/upload-assets/CHANGELOG.md
Labels: patch

#1248 move updating curl version to an auto plugin
  docs/update-curl-version.js
  package.json
  scripts/auto-update-curl-version.js
Labels: internal

#1247 Slack code blocks
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#1249 fix reduce without initial value
  .eslintrc
  packages/core/src/__tests__/git.test.ts
  packages/core/src/changelog.ts
  packages/core/src/git.ts
  packages/core/src/release.ts
  packages/core/src/validate-config.ts
  plugins/all-contributors/src/index.ts
  plugins/npm/src/index.ts
Labels: patch

#1242 Fix missing use of MAVEN_SNAPSHOT_BRANCH
  plugins/maven/src/index.ts
Labels: patch

#1264 calculate next release notes using the latest fork commit not the first
  packages/core/src/auto.ts
Labels: patch

#1262 fix(git): Prevents getLastTagNotInBaseBranch from returning a commit hash
  packages/core/src/__tests__/git.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1265 add more contextual information to next hook
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/npm/__tests__/npm.test.ts
Labels: minor

#1268 add legacyAuth option
  plugins/npm/README.md
  plugins/npm/__tests__/__snapshots__/npm.test.ts.snap
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor
