Repository intuit/auto, pull requests merged in 2020-02, with the labels that each got.

#928 Add gradle plugin to docs website
  docs/index.md
Labels: documentation

#929 dont run git hooks when commiting the version for a single npm package
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#931 add "info" command
  docs/index.md
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/package.json
  packages/core/src/auto.ts
  plugins/maven/src/index.ts
  yarn.lock
Labels: minor

#930 Fix manual git tagging
  plugins/chrome/src/index.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#932 create-labels: handle repos with large amounts of labels
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
Labels: blocked, patch

#933 add info about token permission
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#934 Run `auto info` when any command is run with --verbose
  packages/cli/__tests__/main.test.ts
  packages/cli/package.json
  packages/cli/src/run.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#946 Add gradle to tsconfig.
  tsconfig.dev.json
Labels: patch

#957 Add gradle to root readme
  README.md
Labels: documentation

#958 add clearer docs around github token permissions
  docs/pages/build-platforms/github-actions.md
  docs/pages/extras/release.md
  docs/pages/getting-started.md
Labels: documentation

#960 get node version in crash friendly way
  packages/core/src/auto.ts
Labels: patch

#961 filter out bots in first-time contributor plugins
  packages/core/src/__tests__/make-commit-from-msg.ts
  packages/core/src/log-parse.ts
  plugins/first-time-contributor/__tests__/__snapshots__/first-time-contributor.test.ts.snap
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/first-time-contributor/src/index.ts
Labels: patch

#965 fix: gradle readme use jsonc syntax highlighting
  plugins/gradle/README.md
Labels: documentation

#963 Adding proxyagent to graphql
  packages/core/src/git.ts
Labels: patch

#967 fix case sensitive username bug and handle git errors
  plugins/all-contributors/package.json
  plugins/all-contributors/src/index.ts
Labels: patch

#968 Add new command 'latest' for easier testing and more flexibility
  docs/index.md
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/auto.ts
Labels: minor

#969 ensure remote can be pushed to
  docs/pages/build-platforms/github-actions.md
  docs/pages/build-platforms/jenkins.md
  docs/pages/build-platforms/travis.md
  docs/pages/writing-plugins.md
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-comment.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/remote.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  plugins/chrome/src/index.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/crates/src/index.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/gradle/src/index.ts
  plugins/maven/src/index.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#971 Make all-contributors plugin work for non-lerna packages again
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: patch, skip-release

#972 add warning about using npm plugin with noVersionPrefix
  packages/cli/src/parse-args.ts
  plugins/npm/README.md
Labels: patch

#974 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#977 add git version to 'auto info' output
  packages/core/src/auto.ts
Labels: patch

#975 When parsing owner/repo fallback to parsing 'origin'
  docs/pages/non-npm.md
  docs/pages/troubleshooting.md
  packages/cli/README.md
  packages/core/src/auto.ts
  packages/core/src/utils/__tests__/get-repository.test.ts
  packages/core/src/utils/get-repository.ts
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/npm/__tests__/package-config.test.ts
  plugins/npm/src/index.ts
  plugins/npm/src/package-config.ts
Labels: minor

#990 Better Travis Docs
  docs/pages/build-platforms/travis.md
Labels: documentation

#989 add fallback for when --is-ancestor fails
  packages/core/src/release.ts
Labels: patch

#992 add scoped plugin support
  docs/pages/plugins.md
  packages/core/src/utils/__tests__/load-plugin.test.ts
  packages/core/src/utils/load-plugins.ts
Labels: minor

#997 Add @unknownerror404 as a contributor
  .all-contributorsrc
  README.md
Labels: documentation
