Repository intuit/auto, pull requests merged in 2020-01, with the labels that each got.

#829 fix: prevent slack from default publishing on prerelease branches
  plugins/slack/README.md
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#868 match npm behavior for scoped packages
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch, skip-release

#869 require Node.js >=10.x
  packages/cli/package.json
Labels: major

#870 handle PR numbers that don't exist in repo/fork
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
Labels: patch

#871 Fix running all-contributors when not installed
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: patch

#812 canary: try to match commit to PR if not found in env
  packages/core/src/__tests__/__snapshots__/match-sha-to-pr.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/match-sha-to-pr.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/auto.ts
  packages/core/src/match-sha-to-pr.ts
  packages/core/src/release.ts
Labels: minor

#882 add clearer docs around creating GH_TOKEN
  docs/pages/getting-started.md
  docs/pages/non-npm.md
  docs/pages/troubleshooting.md
  plugins/chrome/src/index.ts
  plugins/maven/src/index.ts
Labels: documentation

#883 Fix onlyPublishWithReleaseLabel w/o labels
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/semver.ts
Labels: patch

#884 fix omitting renovate release notes when a user manually rebases the renovate PR
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/release.test.ts
  packages/core/src/release.ts
Labels: patch

#885 Fix commiting sub-package changelogs
  plugins/npm/src/index.ts
Labels: patch

#887 Add ability to manage sub-package contributor lists
  packages/core/src/auto.ts
  packages/core/src/release.ts
  packages/core/src/utils/get-lerna-packages.ts
  packages/core/src/utils/in-folder.ts
  plugins/all-contributors/README.md
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#888 fallback to 0.0.0 in git-tag plugin with no previous releases
  packages/cli/src/run.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
Labels: patch

#889 Fix error on empty pr body
  packages/core/src/git.ts
Labels: patch

#890 determine first time contributor by using PR count instead of git history
  plugins/first-time-contributor/__tests__/__snapshots__/first-time-contributor.test.ts.snap
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/first-time-contributor/src/index.ts
Labels: patch

#891 add ability to publish exact versions in monorepo
  plugins/npm/README.md
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#892 Surface plugin syntax errors to user
  packages/core/src/utils/__tests__/load-plugin.test.ts
  packages/core/src/utils/__tests__/test-plugin-malformed.js
  packages/core/src/utils/try-require.ts
Labels: patch

#894 Fix private package previous version calculation + Improve dry run messaging
  packages/core/src/auto.ts
  plugins/npm/src/index.ts
Labels: patch

#895 Explicitly add npm & yarn step for all-contributors
  plugins/all-contributors/README.md
Labels: documentation

#897 Add 📦 emoji to canary PR message to make it more noticeable
  packages/core/src/auto.ts
Labels: patch

#896 add better messaging when pr number cannot be detected
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#898 Add html details option to canary hook + Use in npm plugin
  docs/pages/writing-plugins.md
  packages/core/src/auto.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#899 Updated GitHub Action
  docs/pages/build-platforms/github-actions.md
Labels: documentation

#900 Wrap version in code
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: patch

#901 Overhaul "auto init" experience + make it pluggable
  docs/pages/getting-started.md
  docs/pages/writing-plugins.md
  packages/cli/src/parse-args.ts
  packages/cli/src/run.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/init.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/make-hooks.ts
  plugins/jira/src/index.ts
  plugins/npm/src/index.ts
  plugins/slack/src/index.ts
Labels: minor

#912 add ability to store slack hook url in environment variable
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#913 enhance BeforeShipit hook to include the type of release that will be made
  docs/pages/writing-plugins.md
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/crates/__tests__/crates.test.ts
Labels: minor

#915 use different version commit message for independent projects
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch, skip-release

#914 abort release if lerna reports no unchanged packages
  plugins/npm/src/index.ts
Labels: patch

#916 Independent releases
  docs/pages/writing-plugins.md
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/released/src/index.ts
  plugins/twitter/src/index.ts
  plugins/upload-assets/src/index.ts
Labels: minor

#918 updating docs [skip ci]
  docs/pages/non-npm.md
Labels: documentation

#919 better error message running release in repo w/o tags
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#920 add fallback to get lerna json
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#921 move ICommit to "core" to fix external plugin TS build errors
  packages/core/src/git.ts
  packages/core/src/log-parse.ts
  typings/gitlog.d.ts
Labels: patch

#923 Update maven and jenkins documentation (resolves #922)
  docs/pages/build-platforms/jenkins.md
  plugins/maven/README.md
Labels: documentation

#927 fix maven release creation
  plugins/maven/__tests__/maven.test.ts
  plugins/maven/src/index.ts
Labels: patch

#924 Gradle Release Plugin
  plugins/gradle/README.md
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/package.json
  plugins/gradle/src/index.ts
  plugins/gradle/tsconfig.json
  typings/dot-properties.d.ts
  yarn.lock
Labels: minor
