Repository intuit/auto, pull requests merged in 2020-10, with the labels that each got.

#1554 Add pr-body-labels plugin
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/pages/docs/_sidebar.mdx
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  package.json
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/pr-body-labels/README.md
  plugins/pr-body-labels/__tests__/pr-body-labels.test.ts
  plugins/pr-body-labels/package.json
  plugins/pr-body-labels/src/index.ts
  plugins/pr-body-labels/tsconfig.json
  scripts/post-install.sh
  tsconfig.dev.json
Labels: minor

#1555 Improved Docs
  README.md
Labels: documentation

#1556 Pr label body Docs update
  .circleci/config.yml
  plugins/pr-body-labels/README.md
  yarn.lock
Labels: documentation

#1557 chore: updated docs:watch script
  README.md
Labels: documentation

#1561 upgrade gitlog
  packages/core/package.json
  yarn.lock
Labels: patch

#1562 fix diff limit warning in all-contributors plugin
  plugins/all-contributors/src/index.ts
Labels: patch

#1559 Added emojis to README.md
  README.md
Labels: documentation

#1568 fix `next` release prefixing in git-tag plugin
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
Labels: patch

#1569 add invalid-email-address to botlist
  packages/bot-list/src/index.ts
Labels: patch

#1571 add logging if all-contributors rc isn't found or has errors
  plugins/all-contributors/src/index.ts
Labels: patch

#1572 add dryRun to BeforeShipItContext
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  packages/core/src/auto.ts
  plugins/all-contributors/src/index.ts
Labels: minor

#1573 fix erroneous log
  plugins/all-contributors/src/index.ts
Labels: patch

#1576 feat: run pod lib lint during dryrun
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: hacktoberfest, minor

#1575 auto generate contributors if a contributors list exists but none are…
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: hacktoberfest, minor

#1577 add noVersionPrefix to docs
  docs/pages/docs/configuration/autorc.mdx
Labels: documentation

#1580 feat: adding cocoapod verbose logging
  plugins/cocoapods/README.md
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: hacktoberfest-accepted, minor

#1591 Add better verbose logging in gh-pages plugin
  plugins/gh-pages/__tests__/gh-pages.test.ts
  plugins/gh-pages/src/index.ts
Labels: patch

#1599 Support `!` for conventional commits and allow for any conventional-changelog preset
  plugins/conventional-commits/README.md
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/package.json
  plugins/conventional-commits/src/index.ts
  yarn.lock
Labels: minor

#1601 doc: breaking change should bump major not minor
  plugins/conventional-commits/README.md
Labels: documentation

#1603 fix parsing PR body when it's empty
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: patch

#1606 rename afterAddToChangelog hook to afterChangelog
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/all-contributors/__tests__/all-contributors.test.ts
  plugins/all-contributors/src/index.ts
Labels: major

#1604 Run various hooks in a --dry-run
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  docs/pages/docs/plugins/writing-publishing-plugins.mdx
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/utils/get-lerna-packages.ts
  packages/core/src/utils/make-hooks.ts
  plugins/brew/__tests__/brew.test.ts
  plugins/brew/src/index.ts
  plugins/chrome/src/index.ts
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/crates/src/index.ts
  plugins/docker/__tests__/docker.test.ts
  plugins/docker/src/index.ts
  plugins/exec/__tests__/exec.test.ts
  plugins/gem/__tests__/gem.test.ts
  plugins/gem/src/index.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/maven/src/index.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: major

#1609 simplify hook APIs for easier future extensibility
  docs/pages/docs/plugins/changelog-hooks.mdx
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/docker/__tests__/docker.test.ts
  plugins/docker/src/index.ts
  plugins/exec/__tests__/exec.test.ts
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/gem/__tests__/gem.test.ts
  plugins/git-tag/__tests__/git-tag.test.ts
  plugins/git-tag/src/index.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/omit-release-notes/__tests__/omit-release-notes.test.ts
Labels: major

#1618 Git reset bugs on canary/next
  packages/core/src/auto.ts
  plugins/npm/src/index.ts
Labels: patch

#1619 better first-time-contributor thanking
  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  plugins/first-time-contributor/src/index.ts
Labels: patch

#1620 make version, afterVersion, publish, and afterPublish series hooks
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
Labels: patch
