Repository intuit/auto, pull requests merged in 2021-01, with the labels that each got.

#1703 default to patch for 0 non-auto labels on head PR
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/semver.ts
Labels: patch

#1705 fix npm plugin git tag splitting
  plugins/npm/src/index.ts
Labels: patch

#1702 feat: tag canaries for cocoapods plugin
  packages/core/src/auto.ts
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: minor

#1710 fix: add debugging and error handling to exec
  packages/cli/auto
  plugins/exec/__tests__/exec.test.ts
  plugins/exec/package.json
  plugins/exec/src/index.ts
Labels: patch

#1716 add missing configurable option validation
  packages/cli/__tests__/config.test.ts
  packages/core/src/types.ts
  scripts/generate-cofingurable-args.js
Labels: patch

#1717 Attempt to resolve relative plugin paths from extended config location
  docs/pages/docs/configuration/autorc.mdx
  packages/core/src/auto.ts
  packages/core/src/utils/__tests__/load-plugin.test.ts
  packages/core/src/utils/load-plugins.ts
  packages/core/src/utils/test-config/package.json
  packages/core/src/utils/test-config/some-other-plugin.js
  packages/core/src/utils/test-config/some-plugin.js
Labels: minor

#1713 tap the next hook and tag prerelease versions for cocoapods
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: minor

#1720 default `name` and `email` to the token user if no author config is found in autorc or plugin
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: minor

#1722 take into account labels on next+canary PRs
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1725 enable canary releases for upload-assets plugin
  package.json
  packages/cli/auto
  plugins/git-tag/README.md
  plugins/upload-assets/README.md
  plugins/upload-assets/__tests__/upload-assets-ci.test.ts
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/package.json
  plugins/upload-assets/src/index.ts
Labels: minor

#1732 properly kill spawned node child processes
  packages/core/src/utils/verify-auth.ts
Labels: patch

#1735 Properly setting env var _auth for legacyAuth case for npm publish
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#1736 Support "main" as a default "baseBranch"
  README.md
  docs/pages/blog/pr-in-progress.mdx
  docs/pages/blog/using-shipit.mdx
  docs/pages/blog/v8.mdx
  docs/pages/docs/build-platforms/circleci.mdx
  docs/pages/docs/build-platforms/github-actions.mdx
  docs/pages/docs/build-platforms/jenkins.mdx
  docs/pages/docs/build-platforms/travis.mdx
  docs/pages/docs/configuration/autorc.mdx
  docs/pages/docs/extras/changelog.md
  docs/pages/docs/extras/label.md
  docs/pages/docs/extras/shipit.md
  docs/pages/docs/welcome/quick-merge.mdx
  packages/cli/README.md
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/__snapshots__/auto.test.ts.snap
  packages/core/src/__tests__/__snapshots__/changelog.test.ts.snap
  packages/core/src/__tests__/__snapshots__/release.test.ts.snap
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-ci-base-branch.test.ts
  packages/core/src/__tests__/auto-make-changelog.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/__tests__/changelog.test.ts
  packages/core/src/__tests__/get-remote.test.ts
  packages/core/src/__tests__/git.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/__tests__/semver.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/changelog.ts
  packages/core/src/git.ts
  packages/core/src/release.ts
  packages/core/src/types.ts
  packages/core/src/utils/__tests__/verify-auth.test.ts
  packages/core/src/utils/get-current-branch.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/docker/__tests__/docker.test.ts
  plugins/jira/__tests__/jira.test.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
  plugins/released/__tests__/released-label.test.ts
  plugins/vscode/README.md
Labels: minor

#1738 respect `skip` and `none` releases for prereleases
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1739 handle case where auto isn't used in a git repo
  packages/core/src/auto.ts
Labels: patch

#1740 fix jenkins setup
  docs/pages/docs/build-platforms/jenkins.mdx
  package.json
  yarn.lock
Labels: documentation

#1701 Add `@auto-it/magic-zero` Plugin
  README.md
  docs/pages/docs/_sidebar.mdx
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/magic-zero/README.md
  plugins/magic-zero/__tests__/magic-zero.test.ts
  plugins/magic-zero/package.json
  plugins/magic-zero/src/index.ts
  plugins/magic-zero/tsconfig.json
  plugins/npm/__tests__/npm.test.ts
  scripts/template-plugin/README.md
  tsconfig.dev.json
Labels: minor

#1751 format commit message
  plugins/npm/src/index.ts
Labels: patch

#1752 fix commit message when using npx
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1755 update docs site
  docs/pages/_app.js
  docs/pages/_document.js
  docs/pages/blog/why.mdx
  docs/pages/docs/index.mdx
  docs/public/attach-dark-mode.js
  docs/public/logo-dark.png
  docs/public/logo-dark.svg
  docs/public/logo.png
  docs/public/logo.svg
  docs/public/manifest.json
  package.json
  yarn.lock
Labels: documentation

#1756 modify docs site colors
  docs/pages/_document.js
  package.json
  yarn.lock
Labels: documentation

#1757 update ignite
  package.json
  yarn.lock
Labels: documentation

#1759 update ignite
  package.json
  yarn.lock
Labels: documentation

#1760 fix docs meta descriptions
  package.json
  yarn.lock
Labels: documentation

#1762 fix commit message when using npx in non-monorepo
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch
