Repository intuit/auto, pull requests merged in 2021-02, with the labels that each got.

#1772 released plugin: handle PR numbers that dont exist
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: patch

#1773 Fluff up home page
  docs/plugins/home.js
Labels: documentation

#1758 feat: conventional commit plugin will label an unlabeled PR
  packages/core/src/auto.ts
  packages/core/src/semver.ts
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/package.json
  plugins/conventional-commits/src/index.ts
Labels: minor

#1774 don't check if git clean during dry run
  packages/core/src/auto.ts
Labels: patch

#1775 inject next version into bundled "auto"
  packages/cli/package.json
  packages/cli/scripts/inject-version.js
  packages/cli/src/parse-args.ts
Labels: patch

#1776 add --force flag/config option to "next" command
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/types.ts
Labels: minor

#1777 add title option
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#1792 fix running version on prerelease branch with no reachable tags
  packages/core/src/auto.ts
Labels: patch

#1793 add more logging to conventional commits
  plugins/conventional-commits/src/index.ts
Labels: patch

#1791 When calculating "next" lastTag, fallback to latest tag in baseBranch before first commit
  packages/core/src/auto.ts
Labels: patch

#1794 improve jenkins/next docs
  docs/pages/docs/build-platforms/jenkins.mdx
  docs/public/jenkins-next-branches.png
  packages/cli/src/parse-args.ts
  packages/core/src/auto.ts
Labels: documentation

#1797 Do not execute gh-pages build during a dry run
  plugins/gh-pages/__tests__/gh-pages.test.ts
  plugins/gh-pages/src/index.ts
Labels: patch

#1798 update docs to always have latest default labels
  docs/components/defaultLabelsRenderer.js
  docs/pages/docs/configuration/autorc.mdx
  package.json
  yarn.lock
Labels: documentation

#1801 add automated TOC to hooks documentation
  docs/css/syntax-highlighting-overrides.css
  docs/next.config.js
  docs/pages/docs/plugins/changelog-hooks.mdx
  docs/pages/docs/plugins/configuration-hooks.mdx
  docs/pages/docs/plugins/init-hooks.mdx
  docs/pages/docs/plugins/log-parse-hooks.mdx
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
  package.json
  patches/@atomictech+rehype-toc+3.1.2.patch
  yarn.lock
Labels: documentation

#1802 Don't create "Canary Release Assets" during non-canary builds + Change that releases tag to valid semver
  plugins/upload-assets/__tests__/upload-assets-ci.test.ts
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/src/index.ts
Labels: patch

#1803 make canary assets tag at the start of history to avoid tag calculation bugs
  plugins/upload-assets/__tests__/upload-assets-ci.test.ts
  plugins/upload-assets/__tests__/upload-assets.test.ts
  plugins/upload-assets/src/index.ts
Labels: patch

#1804 build the s3 plugin
  tsconfig.dev.json
Labels: patch

#1811 better docs for jira plugin
  plugins/jira/README.md
Labels: patch

#1814 fix typo
  docs/pages/docs/build-platforms/github-actions.mdx
Labels: documentation

#1813 docs: fix broken link on all-contributors page
  plugins/all-contributors/README.md
Labels: documentation

#1812 fix: prefer prerelease tags when determining latest
  .gitignore
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
Labels: patch

#1817 Revert "fix typo"
  docs/pages/docs/build-platforms/github-actions.mdx
Labels: documentation

#1819 fix lerna independent commit message
  docs/pages/docs/build-platforms/github-actions.mdx
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1820 gem's README, typo: you -> your
  plugins/gem/README.md
Labels: documentation

#1827 Use mock-fs for npm tests
  package.json
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  scripts/jest-setup.js
  yarn.lock
Labels: internal

#1829 Add note about verifyAccess config
  plugins/npm/README.md
Labels: documentation

#1828 improve GitHub actions docs + remove unnecessary warning
  docs/pages/docs/build-platforms/github-actions.mdx
  plugins/npm/src/index.ts
Labels: patch
