Repository intuit/auto, pull requests merged in 2021-04, with the labels that each got.

#1937 Update README.md
  plugins/all-contributors/README.md
Labels: documentation

#1938 Update index.ts
  plugins/all-contributors/src/index.ts
Labels: patch

#1936 Prefer npx over yarn for running lerna commands
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/src/index.ts
Labels: patch

#1916 feat(gem): add canary hook
  plugins/gem/__tests__/gem.test.ts
  plugins/gem/package.json
  plugins/gem/src/index.ts
  yarn.lock
Labels: minor

#1942 docs: import INpmConfig from npm package, not from core
  docs/pages/docs/configuration/autorc.mdx
Labels: documentation

#1951 Update docs for "afterAddToChangelog" → "afterChangelog" rename
  docs/pages/docs/plugins/release-lifecycle-hooks.mdx
Labels: documentation

#1967 export CLI API
  packages/cli/src/index.ts
Labels: patch

#1969 canary shouldn't make changes on dry run
  packages/core/src/auto.ts
Labels: patch

#1966 add noDefaultLabels config flag
  docs/pages/docs/configuration/autorc.mdx
  packages/core/src/config.ts
Labels: minor
