Repository intuit/auto, pull requests merged in 2021-03, with the labels that each got.

#1844 fix validating slack config with mixed options
  packages/core/src/__tests__/validate-config.test.ts
  packages/core/src/validate-config.ts
  yarn.lock
Labels: patch

#1846 Expose username, iconUrl, and iconEmoji validation bug + collapse markdown lists into 1 section
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/src/index.ts
Labels: minor

#1848 update getting started docs
  docs/components/get-started-button.js
  docs/components/home.js
  docs/components/label.js
  docs/pages/docs/index.mdx
  docs/pages/docs/welcome/getting-started.mdx
  docs/pages/index.mdx
Labels: documentation

#1849 handle capital X in semver bump list
  plugins/pr-body-labels/__tests__/pr-body-labels.test.ts
  plugins/pr-body-labels/src/index.ts
Labels: patch

#1851 Add leading hyphen to canary identifier so that canaries always sort before any other release type
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
Labels: patch

#1862 Slack message spacing + notification text
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/src/index.ts
Labels: patch

#1865 fix PR label calculation
  packages/core/src/__tests__/auto-canary-local.test.ts
  packages/core/src/auto.ts
Labels: patch

#1864 wrap canary identifier in quotes so terminal understands it's an argument to the --preid flag
  plugins/npm/src/index.ts
Labels: patch

#1866 don't include private packages in canary install list
  packages/core/src/utils/__tests__/get-lerna-packages.test.ts
  packages/core/src/utils/get-lerna-packages.ts
  plugins/npm/src/index.ts
Labels: patch

#1870 fix using --dry-run and --quiet together with the changelog command
  packages/core/src/auto.ts
Labels: patch

#1871 next: handle baseBranch not on remote on fresh repo
  packages/core/src/__tests__/next.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: patch

#1872 Enable authoring pure TypeScript plugins
  docs/pages/docs/plugins/writing-plugins.mdx
  packages/core/package.json
  packages/core/src/auto.ts
  yarn.lock
Labels: minor

#1875 Write auto configuration in TypeScript
  auto.config.ts
  docs/pages/docs/configuration/autorc.mdx
  package.json
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/core/package.json
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/config.ts
  packages/core/src/types.ts
  yarn.lock
Labels: minor

#1876 better exclude for lerna private packages
  packages/core/src/utils/__tests__/get-lerna-packages.test.ts
  packages/core/src/utils/get-lerna-packages.ts
Labels: patch

#1877 only ts-node/register for plugins if typescript is installed to the project
  packages/core/src/auto.ts
Labels: patch

#1885 fix typescript require
  packages/core/src/auto.ts
Labels: patch

#1878 better error message for no NPM_token in CI
  packages/core/src/utils/exec-promise.ts
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/package.json
  plugins/npm/src/index.ts
Labels: patch

#1887 Slack link bug
  plugins/slack/package.json
  plugins/slack/src/index.ts
  yarn.lock
Labels: patch

#1891 Fix ts-node peer deps
  packages/core/package.json
Labels: patch

#1842 Next/Canary Support for Gradle
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
Labels: patch

#1893 add canary target flag/option
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto-in-pr-ci.test.ts
  packages/core/src/auto.ts
  packages/core/src/types.ts
Labels: minor

#1895 Upgrade next-ignite
  docs/components/defaultLabelsRenderer.js
  docs/generate-command-docs.js
  docs/pages/_document.js
  docs/pages/docs/configuration/autorc.mdx
  package.json
  yarn.lock
Labels: dependencies

#1896 Small gradle plugin enhancement
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
Labels: patch

#1907 add Microsoft teams plugins to sidebar and root readme
  README.md
  docs/pages/docs/_sidebar.mdx
  plugins/microsoft-teams/README.md
Labels: documentation

#1908 add slack release notes screenshot
  plugins/slack/README.md
Labels: documentation

#1909 add skip label docs
  docs/pages/docs/configuration/autorc.mdx
Labels: documentation

#1911 add defaultReleaseType option
  plugins/conventional-commits/README.md
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/src/index.ts
Labels: minor

#1912 update skip docs
  docs/pages/docs/configuration/autorc.mdx
Labels: documentation

#1913 fix rendering long lines in slack plugin
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: patch

#1723 Fix conventional commits releaseType calculation to include all conventionally committed commits in PR
  plugins/conventional-commits/__tests__/conventional-commits.test.ts
  plugins/conventional-commits/package.json
  plugins/conventional-commits/src/index.ts
Labels: minor

#1929 Release Command: Tag creation fallback.
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/git.ts
Labels: minor

#1930 Enable using globally installed plugins
  packages/core/package.json
  packages/core/src/utils/try-require.ts
  scripts/jest-setup.js
  typings/requireg.d.ts
  yarn.lock
Labels: patch
