Repository intuit/auto, pull requests merged in 2021-05, with the labels that each got.

#1971 add noDefaultLabels config option to the globalOptions type
  packages/core/src/types.ts
Labels: patch

#1976 rearrange to allow dryrun to leverage prefixed tag
  plugins/git-tag/src/index.ts
Labels: patch

#1962 add sbt plugin
  README.md
  docs/pages/docs/_sidebar.mdx
  plugins/sbt/README.md
  plugins/sbt/__tests__/sbt.test.ts
  plugins/sbt/package.json
  plugins/sbt/src/index.ts
  plugins/sbt/tsconfig.json
  tsconfig.dev.json
  yarn.lock
Labels: minor

#1947 Remove `text` from non-app authed slack response
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/src/index.ts
Labels: patch

#1982 feat: push multiple podspecs
  plugins/cocoapods/README.md
  plugins/cocoapods/__tests__/cocoapods.test.ts
  plugins/cocoapods/src/index.ts
Labels: minor

#1914 Feature/msteams
  package.json
  packages/core/package.json
  packages/core/src/__tests__/auto-env.test.ts
  packages/core/src/__tests__/release.test.ts
  packages/core/src/git.ts
  packages/core/src/log-parse.ts
  plugins/brew/__tests__/brew.test.ts
  plugins/crates/__tests__/crates.test.ts
  plugins/maven/__tests__/maven.test.ts
  plugins/microsoft-teams/README.md
  plugins/microsoft-teams/__tests__/__snapshots__/index.test.ts.snap
  plugins/microsoft-teams/__tests__/__snapshots__/microsoft-teams.test.ts.snap
  plugins/microsoft-teams/__tests__/index.test.ts
  plugins/microsoft-teams/package.json
  plugins/microsoft-teams/src/index.ts
  plugins/npm/__tests__/monorepo-log.test.ts
  scripts/jest-setup.js
  yarn.lock
Labels: minor

#1997 fix(npm): Prevents canary releases with double dashed version numbers
  plugins/npm/src/index.ts
Labels: patch

#1998 fix publish
  auto.config.ts
  package.json
  patches/next-ignite+0.10.11.patch
  yarn.lock
Labels: patch

#2001 Fix broken link to /generated/omit-commits
  docs/pages/docs/plugins/log-parse-hooks.mdx
Labels: documentation
