Repository intuit/auto, pull requests merged in 2022-03, with the labels that each got.

#2064 fix(@octokit/request-error) Fixes depreciation error when accessing error.headers
  packages/core/package.json
  packages/core/src/__tests__/git.test.ts
  yarn.lock
Labels: patch

#2115 feat(plugins/npm): add support for passing publishFolder.
  plugins/npm/README.md
  plugins/npm/__tests__/npm-next.test.ts
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#2036 feat(plugins/npm): exclude pre-release branches from greaterRelease calculation
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#2158 fix: update node-fetch
  packages/core/package.json
  plugins/microsoft-teams/package.json
  plugins/slack/package.json
  yarn.lock
Labels: minor

#2152 Improve gem deployment
  package.json
  plugins/gem/__tests__/gem.test.ts
  plugins/gem/src/index.ts
  yarn.lock
Labels: minor

#2160 [Gradle] Fix canary version reporting
  plugins/gradle/__tests__/gradle.test.ts
  plugins/gradle/src/index.ts
Labels: patch

#2169 CocoaPods swap promise.all for reduce to avoid git locking problem
  plugins/cocoapods/src/index.ts
Labels: patch

#2166 Add `lockPrs` option for released plugin
  plugins/released/__tests__/released-label.test.ts
  plugins/released/src/index.ts
Labels: minor

#2161 docs: fix publishFolder example
  plugins/npm/README.md
Labels: documentation

#2162 docs: add react-easy-crop to "Projects Using auto"
  README.md
Labels: documentation

#2165 fix(npm): remove quote in commit message for standalone packages
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: patch

#2164 Allow load npm module as extends
  docs/pages/docs/configuration/autorc.mdx
  packages/core/src/__tests__/config.test.ts
  packages/core/src/config.ts
Labels: minor

#2171 Update octokit
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/__tests__/git.test.ts
  packages/core/src/git.ts
  plugins/all-contributors/package.json
  plugins/all-contributors/src/index.ts
  plugins/cocoapods/src/index.ts
  plugins/conventional-commits/package.json
  plugins/exec/package.json
  plugins/first-time-contributor/package.json
  plugins/gem/package.json
  plugins/gh-pages/package.json
  plugins/npm/package.json
  plugins/released/package.json
  plugins/slack/package.json
  plugins/twitter/package.json
  plugins/upload-assets/package.json
  yarn.lock
Labels: patch

#2172 Fix loading object author from auto rc
  packages/core/src/__tests__/validate-config.test.ts
  packages/core/src/types.ts
Labels: patch

#1972 add mergify[bot] to the bot-list
  packages/bot-list/src/index.ts
Labels: patch

#2174 Gem: use releaseCommand in canary release
  plugins/gem/__tests__/gem.test.ts
  plugins/gem/src/index.ts
Labels: patch

#2175 create major version at last release tag
  packages/core/src/__tests__/major-version-branches.test.ts
  packages/core/src/auto.ts
Labels: patch

#2176 Fix typo in maven/README.md
  plugins/maven/README.md
Labels: documentation
