Repository intuit/auto, pull requests merged in 2023-02, with the labels that each got.

#2256 (docker plugin) fix git tagging command
  plugins/docker/__tests__/docker.test.ts
  plugins/docker/src/index.ts
Labels: patch

#2288 chore: fix typo
  packages/cli/src/run.ts
Labels: documentation

#2262 fix: init command add .env to .gitignore
  packages/core/src/init.ts
Labels: patch

#2272 Slack: Update atTarget option to disable tagging messages
  plugins/slack/README.md
  plugins/slack/__tests__/__snapshots__/slack.test.ts.snap
  plugins/slack/__tests__/slack.test.ts
  plugins/slack/src/index.ts
Labels: minor

#2210 Create Protected branch plugin
  README.md
  docs/pages/docs/_sidebar.mdx
  plugins/protected-branch/README.md
  plugins/protected-branch/__tests__/protected-branch.test.ts
  plugins/protected-branch/doc/branch-protection-1.png
  plugins/protected-branch/doc/branch-protection-2.png
  plugins/protected-branch/package.json
  plugins/protected-branch/src/GitOperator.ts
  plugins/protected-branch/src/index.ts
  plugins/protected-branch/tsconfig.json
  tsconfig.dev.json
  yarn.lock
Labels: minor

#2298 this was throwing an error when it didn't have to causing an odd error in the magic zero plugin
  packages/core/src/auto.ts
Labels: patch

#2299 switch to github actions
  .circleci/config.yml
  .github/actions/build-cache/action.yml
  .github/actions/install-deps/action.yml
  .github/workflows/build.yml
  packages/cli/package.json
  packages/core/src/__tests__/remote.test.ts
  plugins/gradle/__tests__/gradle.test.ts
  yarn.lock
Labels: internal

#2318 run actions on PRs
  .github/workflows/build.yml
Labels: internal

#2189 non-zero exit code if commit is behind
  packages/core/src/auto.ts
Labels: minor

#2277 feat(npm): use version commit message from lerna.json
  plugins/npm/__tests__/npm.test.ts
  plugins/npm/src/index.ts
Labels: minor

#2258 Add `--no-git-commit` option to `changelog` command
  packages/cli/src/parse-args.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto-args.ts
  packages/core/src/auto.ts
  packages/core/src/release.ts
Labels: minor

#2317 Improve protected branch plugin
  plugins/protected-branch/__tests__/protected-branch.test.ts
  plugins/protected-branch/src/GitOperator.ts
  plugins/protected-branch/src/index.ts
Labels: minor

#2182 Feat add `afterRun` hook
  docs/pages/docs/plugins/configuration-hooks.mdx
  packages/cli/src/run.ts
  packages/core/src/__tests__/auto.test.ts
  packages/core/src/auto.ts
  packages/core/src/utils/make-hooks.ts
Labels: minor

#2329 fix PR number detection in build action
  .github/workflows/build.yml
Labels: internal

#2330 chore: fix prompt message
  packages/core/src/init.ts
Labels: patch
